/* ===== ORDER FLOW ===== */
const CO_STEPS=['Choose Package','Your Brand','Materials','Delivery','Summary & Pay'];
const MATS=[['logo','Logo','image','Logo_BhojKitchen.png'],['img','Product images','image','Kacchi_platter_01.jpg'],['vid','Product video','video','Kitchen_broll.mp4'],['script','Script','doc','Script_draft_v1.docx'],['guide','Brand guidelines','file','Brand_guidelines.pdf'],['ref','Reference videos','video','Reference_reel_link.txt']];
function addDays(n){const d=new Date(2026,9,3+n);return d.toISOString().slice(0,10);}
function niceDate(s){const d=new Date(s+'T00:00:00');return isNaN(d)?s:d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'});}
function coInit(cid,p){if(!S.co||S.co.c!==cid){S.co={c:cid,pkg:p!=null&&p!==''?+p:1,step:1,files:{},date:addDays(7),format:'9:16 vertical',plats:new Set(['Facebook','Instagram']),pay:'bkash',
 brief:{biz:'Bhoj Kitchen',web:'bhojkitchen.com.bd',product:'Friday family kacchi platter (serves 4)',aud:'Families and office groups in Dhanmondi, age 22–45',goal:'Drive weekend table bookings',lang:'Bangla',tone:'Warm and family-friendly',notes:'Mention the 15% weekend discount and show a close-up of the platter.'}};}
 else if(p!=null&&p!==''&&S.co.step===1)S.co.pkg=+p;}
PAGES.order=(cid,p)=>{const c=C(cid)||C('c1');coInit(c.id,p);const co=S.co,P=pkgs(c),pk=P[co.pkg];
 return `<div class="phead" style="padding-block:22px"><div class="wrap"><div class="crumbs"><button data-go="explore">Explore</button>${ic('chevr')}<button data-go="creator~${c.id}">${esc(c.name)}</button>${ic('chevr')}<span>Order</span></div><h1 style="font-size:clamp(26px,3vw,34px)">Order a promotional video</h1></div></div>
 <div class="wrap co"><div style="min-width:0"><div class="stepper">${CO_STEPS.map((s,i)=>`<button class="${i+1<co.step?'done':''} ${i+1===co.step?'on':''}" data-act="coGo" data-n="${i+1}"><small>Step ${i+1}</small><span>${s}</span></button>`).join('')}</div>
 <div class="card pad" style="padding:clamp(18px,3vw,28px)" id="co-step">${coStep(c)}</div>
 <div class="row between" style="margin-top:18px">${co.step>1?`<button class="btn btn-ghost" data-act="coGo" data-n="${co.step-1}">${ic('chevl')}Back</button>`:`<button class="btn btn-ghost" data-go="creator~${c.id}">${ic('chevl')}Back to profile</button>`}
 ${co.step<5?`<button class="btn btn-pri" data-act="coGo" data-n="${co.step+1}">Continue${ic('chevr')}</button>`:`<button class="btn btn-pri btn-lg" data-act="pay">${ic('lock')}Pay Securely · ${tk(pk.price)}</button>`}</div></div>
 <aside class="stack" style="position:sticky;top:88px">${coSummary(c)}</aside></div>`;};
function coSummary(c){const co=S.co,pk=pkgs(c)[co.pkg];return `<div class="card pad stack" style="gap:14px"><div class="row">${av(c,48)}<div><b>${esc(c.name)} ${vb()}</b><div class="small muted">${c.cats[0]} · ${c.city}</div></div></div>
 <div style="padding:12px;border-radius:10px;background:var(--bg-2)"><b>${pk.n} package</b><div class="small muted">${pk.desc} · ${pk.days}-day delivery · ${pk.rev} revision${pk.rev>1?'s':''}</div></div>
 <div class="sumrow"><span>Creator fee</span><span class="tnum">${tk(pk.price)}</span></div><div class="sumrow"><span>BitPromo service &amp; protection fee</span><span class="tnum" style="color:var(--good);font-weight:650">Included</span></div>
 <div class="sumrow total"><span>Total</span><span class="tnum">${tk(pk.price)}</span></div>
 <div class="protect">${ic('shield')}<span>Your money is protected. BitPromo holds the payment until you approve the video.</span></div>
 <p class="small muted">BitPromo’s 20% commission (${tk(pk.price*.2)}) comes out of the creator’s earnings, not your bill.</p></div>`;}
function coStep(c){const co=S.co,P=pkgs(c),b=co.brief;const inp=(k,l,ph,full)=>`<div class="${full?'full':''}"><label for="co-${k}">${l}</label><input class="field" id="co-${k}" data-co="${k}" value="${esc(b[k])}" placeholder="${ph}"></div>`;
 const selF=(k,l,opts)=>`<div><label for="co-${k}">${l}</label><select class="field" id="co-${k}" data-co="${k}">${opts.map(o=>`<option ${b[k]===o?'selected':''}>${o}</option>`).join('')}</select></div>`;
 if(co.step===1)return `<h2 style="font-size:22px">Choose your package</h2><p class="muted" style="margin:6px 0 18px">All packages include BitPromo payment protection and a quality check.</p><div class="pkg-pick">${P.map((p,i)=>`<button class="pkg-opt ${i===co.pkg?'on':''}" data-act="coPkg" data-i="${i}"><span class="row between"><b>${p.n}</b>${i===co.pkg?`<span class="vbadge">${ic('check')}</span>`:''}</span><span class="pkg-price" style="font-size:24px">${tk(p.price)}</span><span class="small muted">${p.desc}</span><span class="small">${ic('clock')} ${p.days} days · ${ic('refresh')} ${p.rev} rev.</span><span class="small muted">${FEATS.filter(([k])=>p.f[k]).map(([,l])=>l).join(' · ')}</span></button>`).join('')}</div>`;
 if(co.step===2)return `<h2 style="font-size:22px">Tell us about your brand</h2><p class="muted" style="margin:6px 0 18px">A clear brief is how the creator, and our quality check, know what “done” looks like. <span class="tag">Sample brief filled in for the demo</span></p>
 <div class="form">${inp('biz','Business name','Your business name')}${inp('web','Website or Facebook page','www…')}${inp('product','Product or service to promote','What should the video feature?',1)}${inp('aud','Target audience','Who should this reach?',1)}${inp('goal','Campaign objective','e.g. more bookings, app installs')}${selF('lang','Preferred language',['Bangla','English','Bangla + English','Hindi'])}${selF('tone','Tone',['Warm and family-friendly','Energetic and fun','Premium and elegant','Informative and trustworthy','Comedic'])}
 <div class="full"><label for="co-notes">Anything the creator must say or show?</label><textarea class="field" id="co-notes" data-co="notes">${esc(b.notes)}</textarea></div></div>`;
 if(co.step===3)return `<h2 style="font-size:22px">Upload your materials</h2><p class="muted" style="margin:6px 0 18px">Optional. You can also share files later in the order chat. <button class="btn-link" data-act="coSample">Add sample files</button></p>
 <div class="grid g2" style="gap:14px">${MATS.map(([k,l,i])=>`<div class="drop"><div class="drop-head"><span class="fi">${ic(i)}</span><div class="grow"><b style="font-size:14.5px">${l}</b><div class="small muted">${(co.files[k]||[]).length?`${co.files[k].length} file${co.files[k].length>1?'s':''} added`:'No files yet'}</div></div><label class="btn btn-ghost btn-sm" for="up-${k}" style="cursor:pointer">${ic('upload')}Upload</label><input type="file" id="up-${k}" data-up="${k}" multiple hidden></div>${(co.files[k]||[]).length?`<div class="row" style="gap:6px">${co.files[k].map(f=>`<span class="filechip">${ic('check')}${esc(f)}</span>`).join('')}</div>`:''}</div>`).join('')}</div>`;
 if(co.step===4)return `<h2 style="font-size:22px">Delivery requirements</h2><p class="muted" style="margin:6px 0 18px">${pkgs(c)[co.pkg].n} package delivers in ${pkgs(c)[co.pkg].days} days. Pick a date on or after that.</p>
 <div class="form"><div><label for="co-date">Expected delivery date</label><input type="date" class="field" id="co-date" data-cod="date" value="${co.date}" min="${addDays(pkgs(c)[co.pkg].days)}"></div><div></div>
 <div class="full"><label>Video format</label><div class="chips">${['9:16 vertical','16:9 landscape','1:1 square'].map(f=>`<button class="chipt ${co.format===f?'on':''}" data-act="coFmt" data-v="${f}">${f}</button>`).join('')}</div></div>
 <div class="full"><label>Where will you post it?</label><div class="chips">${['Facebook','Instagram','TikTok','YouTube','Website','Other'].map(f=>`<button class="chipt ${co.plats.has(f)?'on':''}" data-act="coPlat" data-v="${f}">${co.plats.has(f)?ic('check'):''}${f}</button>`).join('')}</div></div></div>`;
 const pk=P[co.pkg],nf=Object.values(co.files).flat().length;
 return `<h2 style="font-size:22px">Order summary</h2><p class="muted" style="margin:6px 0 18px">Check the details, choose how to pay, and BitPromo will hold your payment until you approve the video.</p>
 <div class="grid g2" style="gap:14px">${[['Package',`${pk.n} · ${pk.desc}`,1],['Business',b.biz||'—',2],['Promoting',b.product||'—',2],['Audience',b.aud||'—',2],['Language & tone',`${b.lang} · ${b.tone}`,2],['Delivery',`${niceDate(co.date)} · ${co.format}`,4],['Platforms',[...co.plats].join(', ')||'—',4],['Materials',nf?`${nf} file${nf>1?'s':''} attached`:'None yet',3]].map(([k,v,s])=>`<div style="padding:12px 14px;border:1px solid var(--line);border-radius:10px;min-width:0"><div class="row between"><span class="small muted" style="font-weight:650">${k}</span><button class="btn-link small" data-act="coGo" data-n="${s}">Edit</button></div><div style="font-weight:600;overflow-wrap:anywhere">${esc(v)}</div></div>`).join('')}</div>
 <h3 style="margin:26px 0 12px">Payment method</h3><div class="paym">${[['bkash','bKash','#E2136E'],['nagad','Nagad','#EC1C24'],['card','Card','#1F2A44'],['bank','Bank','#0F9F6E']].map(([k,l,col])=>`<button class="${co.pay===k?'on':''}" data-act="coPay" data-v="${k}"><span class="lg" style="background:${col}">${l.slice(0,2).toUpperCase()}</span>${l}</button>`).join('')}</div>
 <div class="demo-note" style="margin-top:16px">${ic('alert')}Prototype: no real payment is taken. bKash, Nagad, card and bank options are shown for design only.</div>`;}
document.addEventListener('input',e=>{const t=e.target;if(t.dataset&&t.dataset.co&&S.co)S.co.brief[t.dataset.co]=t.value;if(t.dataset&&t.dataset.cod&&S.co)S.co[t.dataset.cod]=t.value;});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset&&t.dataset.co&&S.co)S.co.brief[t.dataset.co]=t.value;if(t.dataset&&t.dataset.up&&S.co){const k=t.dataset.up;S.co.files[k]=[...(S.co.files[k]||[]),...[...t.files].map(f=>f.name)];coRefresh();toast(`${t.files.length} file${t.files.length>1?'s':''} added`);}
 if(t.dataset&&t.dataset.vup){S.ver.files[t.dataset.vup]=t.files[0]?.name||'document.jpg';render();}});
function coRefresh(){render();const el=$('.stepper');if(el)el.scrollIntoView({block:'nearest'});}
ACT.coGo=el=>{const n=+el.dataset.n;if(S.co.step===2&&n>2&&!S.co.brief.biz.trim()){toast('Add your business name to continue');return;}S.co.step=n;render();window.scrollTo({top:0});};
ACT.coPkg=el=>{S.co.pkg=+el.dataset.i;render();};
ACT.coSample=()=>{MATS.forEach(([k,,,f])=>{if(!(S.co.files[k]||[]).length)S.co.files[k]=[f];});render();toast('Sample files attached');};
ACT.coFmt=el=>{S.co.format=el.dataset.v;render();};
ACT.coPlat=el=>{const v=el.dataset.v;S.co.plats.has(v)?S.co.plats.delete(v):S.co.plats.add(v);render();};
ACT.coPay=el=>{S.co.pay=el.dataset.v;render();};
ACT.pay=()=>{const co=S.co,c=C(co.c),pk=pkgs(c)[co.pkg];const method={bkash:'bKash',nagad:'Nagad',card:'Card',bank:'Bank transfer'}[co.pay];
 modal(`<div class="modal-body" style="text-align:center;padding:40px 24px"><div class="spinner"></div><h3>Securing your payment</h3><p class="muted">Sending ${tk(pk.price)} via ${method} to BitPromo payment protection…</p></div>`);
 setTimeout(()=>{const id='BP-'+(S.nextId++);ORDERS.unshift({id,b:ME_BIZ,c:c.id,pkg:co.pkg,title:`${pk.desc}: ${co.brief.product||'your product'}`,st:1,created:'Oct 03',due:niceDate(co.date),revUsed:0,brief:{...co.brief,plats:[...co.plats].join(', '),format:co.format},files:Object.values(co.files).flat(),paid:method});
  S.role='biz';S.co=null;
  modal(`<div class="modal-body" style="text-align:center;padding:36px 26px"><div class="success-ic">${ic('check')}</div><h2 style="font-size:26px">Order placed</h2><p class="muted">Order <b class="tnum" style="color:var(--ink)">${id}</b> is with ${esc(c.name)}. Your ${tk(pk.price)} is held by BitPromo until you approve the video.</p>
  <div class="stack" style="gap:10px;margin-top:8px"><button class="btn btn-pri btn-block" data-go="track~${id}">Track your order</button><button class="btn btn-ghost btn-block" data-go="dash~biz~home">Go to dashboard</button></div></div>`);},1500);};

/* ===== ORDER TRACKING ===== */
const defBrief=o=>({biz:B(o.b).name,product:o.title,aud:'Young adults and families in '+B(o.b).city+', age 20–40',goal:'Increase awareness and drive orders',lang:'Bangla',tone:'Warm and friendly',plats:'Facebook, Instagram',format:'9:16 vertical',notes:'Show the logo in the first 3 seconds and end with the offer.'});
PAGES.track=id=>{const o=O(id)||ORDERS[0],c=C(o.c),b=B(o.b),P=pkgs(c)[o.pkg],role=S.role||'biz',br=o.brief||defBrief(o),A=amt(o);const back=role==='creator'?'dash~creator~orders':role==='admin'?'dash~admin~orders':'dash~biz~orders';
 const files=o.files&&o.files.length?o.files:['Logo_'+b.name.replace(/\W/g,'')+'.png','Product_photo_01.jpg','Brand_guidelines.pdf'];
 return `<div class="phead"><div class="wrap"><div class="crumbs"><button data-go="${back.replace(/~[a-z]+$/,'~home')}">Dashboard</button>${ic('chevr')}<button data-go="${back}">Orders</button>${ic('chevr')}<span>${o.id}</span></div>
 <div class="row between"><div><h1 style="font-size:clamp(24px,3vw,34px)">${esc(o.title)}</h1><div class="row small muted" style="margin-top:8px;gap:14px">${stagePill(o.st)}<span class="tnum">Order ${o.id}</span><span>Placed ${o.created}</span><span>Due ${o.due}</span></div></div>
 <div class="row"><button class="btn btn-ghost btn-sm" data-act="contact" data-id="${c.id}">${ic('message')}Messages</button><button class="btn btn-ghost btn-sm" data-act="dispute" data-id="${o.id}">${ic('flag')}Report a problem</button></div></div>
 <div class="hstl" style="margin-top:24px">${STAGES.map((s,i)=>`<div class="${i<o.st||o.st===7?'done':''} ${i===o.st&&o.st<7?'cur':''}">${s}</div>`).join('')}</div></div></div>
 <div class="wrap co"><div class="stack" style="gap:20px;min-width:0">
 <section class="card pad stack" style="gap:16px"><div class="row between"><h3>Delivery</h3>${o.st>=4?`<span class="tag">${P.dur} sec · ${br.format}</span>`:''}</div>
 <div class="dgrid">${o.st>=4?vt(c,{r:'v',title:o.title,brand:b.name,dur:P.dur,sub:o.st>=7?'Final video':'Draft for review'}):`<div class="vt v" style="--a:var(--bg-2);--b:var(--line);display:grid;place-items:center;cursor:default"><div style="position:relative;z-index:3;color:var(--muted);text-align:center;padding:16px;font-size:13px">${ic('video')}<br>The video appears here once ${first(c)} submits it</div></div>`}
 <div class="stack" style="gap:14px">${trackAction(o,role,c,b,P,A)}</div></div></section>
 ${o.st>=5?`<section class="card pad"><h3 style="margin-bottom:12px">BitPromo quality check</h3><ul class="checks">${[`Duration matches package (${P.dur} sec)`,`${b.name} name and logo visible`,'Offer and price text match the brief','Clear audio, no background noise',`Format is ${br.format}`].map(x=>`<li>${o.st===5?`<span class="muted">${ic('clock')}</span>`:ic('check')}${x}</li>`).join('')}</ul>${o.st===5?'<p class="small muted" style="margin-top:10px">Our team is reviewing the draft against your brief.</p>':'<p class="small muted" style="margin-top:10px">Passed by BitPromo QA · Oct 03</p>'}</section>`:''}
 <section class="card pad"><h3 style="margin-bottom:14px">Campaign brief</h3><div class="grid g2" style="gap:12px 24px">${[['Business',br.biz],['Promoting',br.product],['Audience',br.aud],['Objective',br.goal],['Language',br.lang],['Tone',br.tone],['Platforms',br.plats],['Must include',br.notes]].map(([k,v])=>`<div style="min-width:0"><div class="small muted" style="font-weight:650">${k}</div><div style="overflow-wrap:anywhere">${esc(v)}</div></div>`).join('')}</div>
 <h4 style="margin:20px 0 10px">Files</h4><div class="row" style="gap:8px">${files.map(f=>`<span class="filechip">${ic('file')}${esc(f)}</span>`).join('')}</div></section></div>
 <aside class="stack" style="gap:20px">
 <div class="card pad stack" style="gap:12px"><div class="row">${av(c,44)}<div class="grow"><div class="small muted">Creator</div><b>${esc(c.name)} ${vb()}</b></div></div><div class="row">${bizAv(b,44)}<div class="grow"><div class="small muted">Business</div><b>${esc(b.name)}</b></div></div>
 <div class="sumrow" style="border-top:1px solid var(--line);padding-top:12px"><span class="muted">Package</span><span>${P.n} · ${P.dur} sec</span></div><div class="sumrow"><span class="muted">Order value</span><b class="tnum">${tk(A)}</b></div><div class="sumrow"><span class="muted">Revisions</span><span>${o.revUsed} of ${P.rev} used</span></div><div class="sumrow"><span class="muted">Deadline</span><span>${o.due}</span></div>
 <div class="protect" style="${o.st===7?'':''}">${ic(o.st===7?'check':'lock')}<span>${o.st===7?`Payment released: ${esc(first(c))} received ${tk(A*.8)}, BitPromo commission ${tk(A*.2)}.`:`${tk(A)} held by BitPromo payment protection.`}</span></div></div>
 <div class="card pad"><h3 style="margin-bottom:16px">Order status</h3><ol class="tl">${STAGES.map((s,i)=>{const cls=i<o.st||o.st===7?'done':i===o.st?'cur':'todo';return `<li class="${cls}"><span class="dot">${cls==='done'?ic('check'):i+1}</span><div><b>${s}</b><small>${STAGE_NOTE[i]}</small></div></li>`;}).join('')}</ol></div>
 ${o.st<7?`<div class="demo-note" style="flex-direction:column;align-items:stretch;gap:10px"><span class="row" style="gap:8px">${ic('sliders')}<b style="color:var(--ink)">Prototype control</b></span><span>Move this order forward to show each stage of the flow.</span><button class="btn btn-ghost btn-sm" data-act="advance" data-id="${o.id}">Move to “${STAGES[o.st+1]}”</button></div>`:''}</aside></div>`;};
function trackAction(o,role,c,b,P,A){
 if(o.st===7)return `<div class="row" style="gap:10px"><span class="success-ic" style="width:44px;height:44px;margin:0">${ic('check')}</span><div><h3>Order completed</h3><p class="muted small">Approved and paid out. The final file is ready to download.</p></div></div><div class="row"><button class="btn btn-pri btn-sm" data-act="toastMsg" data-m="Download starts in the live product">Download video</button><button class="btn btn-ghost btn-sm" data-go="order~${c.id}~${o.pkg}">Order again</button></div>
 ${role==='biz'?(o.reviewed?`<div class="protect">${ic('star')}<span>Thanks, your review is published on ${first(c)}'s profile.</span></div>`:`<div style="border-top:1px solid var(--line);padding-top:14px" class="stack"><b>Rate ${first(c)}</b><div class="row" id="rate" style="gap:4px">${[1,2,3,4,5].map(n=>`<button class="iconbtn" data-act="rate" data-n="${n}" aria-label="${n} stars" style="color:${n<=(S.rate||5)?'var(--gold)':'var(--muted)'}">${ic('star','i-fill')}</button>`).join('')}</div><textarea class="field" id="rev-text" placeholder="How was working with ${first(c)}?">Great communication and delivered the video exactly according to the brief.</textarea><button class="btn btn-dark btn-sm" style="align-self:flex-start" data-act="review" data-id="${o.id}">Publish review</button></div>`):''}`;
 if(o.st===6){if(role==='biz')return `<div><h3>Your video is ready to review</h3><p class="muted small" style="margin-top:4px">It passed BitPromo’s quality check. Approve it to release ${tk(A*.8)} to ${first(c)}, or ask for changes.</p></div><div class="row"><button class="btn btn-good" data-act="approve" data-id="${o.id}">${ic('check')}Approve &amp; release payment</button><button class="btn btn-ghost" data-act="revise" data-id="${o.id}" ${o.revUsed>=P.rev?'disabled':''}>${ic('refresh')}Request revision (${P.rev-o.revUsed} left)</button></div><p class="small muted">If you don’t respond within 3 days, the order is approved automatically.</p>`;
  return `<h3>Waiting for ${esc(b.name)} to review</h3><p class="muted small">The draft passed quality check. Payment is released when the buyer approves.</p>`;}
 if(o.st===5)return role==='admin'?`<h3>Quality check</h3><p class="muted small">Compare the draft with the brief, then pass or return it.</p><div class="row"><button class="btn btn-good" data-act="advance" data-id="${o.id}">Pass quality check</button><button class="btn btn-ghost" data-act="toastMsg" data-m="Returned to creator with notes">Return to creator</button></div>`:`<h3>BitPromo is checking the video</h3><p class="muted small">We compare the draft with your brief: duration, branding, offer text, audio and format.</p>`;
 if(o.st===4)return `<h3>Draft video submitted</h3><p class="muted small">${first(c)} uploaded the draft. It goes to BitPromo’s quality check next.</p>`;
 if(o.st>=2)return role==='creator'?`<h3>You’re in production</h3><p class="muted small">Upload the draft when it’s ready. Deadline: ${o.due}.</p><button class="btn btn-pri" style="align-self:flex-start" data-act="upVideo" data-id="${o.id}">${ic('upload')}Upload video</button>`:`<h3>${first(c)} is ${o.st===2?'preparing to film':'filming your video'}</h3><p class="muted small">Delivery expected by ${o.due}. You can message ${first(c)} any time.</p>`;
 return role==='creator'?`<h3>New order request</h3><p class="muted small">${esc(b.name)} sent a brief for ${P.n} (${tk(A)}). You’ll receive ${tk(A*.8)} after approval.</p><div class="row"><button class="btn btn-good" data-act="accept" data-id="${o.id}">Accept order</button><button class="btn btn-ghost" data-act="toastMsg" data-m="Declined. The buyer is refunded in full.">Decline</button></div>`:`<h3>Waiting for ${first(c)} to accept</h3><p class="muted small">Creators usually reply within ${c.resp}. Your payment is safe with BitPromo.</p>`;}
ACT.advance=el=>{const o=O(el.dataset.id);if(o.st<7)o.st++;toast(`Order moved to “${STAGES[o.st]}”`);render();};
ACT.accept=el=>{const o=O(el.dataset.id);o.st=2;toast('Order accepted. Time to plan the shoot!');render();};
ACT.upVideo=el=>{const o=O(el.dataset.id);o.st=4;toast('Video uploaded and sent to quality check');render();};
ACT.approve=el=>{const o=O(el.dataset.id);o.st=7;toast(`Approved. ${tk(amt(o)*.8)} released to ${C(o.c).name}`);render();};
ACT.revise=el=>{const o=O(el.dataset.id);modal(`${mhead('Request a revision')}<form class="modal-body" data-form="revise" data-id="${o.id}"><p class="muted">Explain what should change. Revisions must stay within the original brief.</p><textarea class="field" name="t" id="rev-note" required>Please make the platter close-up longer and say the discount at the end too.</textarea><button class="btn btn-pri" type="submit">Send revision request</button></form>`);};
FORM.revise=f=>{const o=O(f.dataset.id);o.revUsed++;o.st=3;closeModal();toast('Revision requested. The creator has been notified.');render();};
ACT.rate=el=>{S.rate=+el.dataset.n;$$('#rate button').forEach((b,i)=>b.style.color=i<S.rate?'var(--gold)':'var(--muted)');};
ACT.review=el=>{const o=O(el.dataset.id);o.reviewed=true;REVIEWS.unshift({b:o.b,c:o.c,stars:S.rate||5,date:'Oct 03',text:($('#rev-text')||{}).value||'Great work.'});toast('Review published');render();};
ACT.dispute=el=>modal(`${mhead('Report a problem')}<form class="modal-body" data-form="dispute"><p class="muted">BitPromo reviews the order brief, messages and files, then decides fairly for both sides.</p><div><label class="small" style="font-weight:650" for="dp-r">What went wrong?</label><select class="field" id="dp-r"><option>Video doesn’t match the brief</option><option>Missed deadline</option><option>Creator not responding</option><option>Other</option></select></div><textarea class="field" id="dp-t" placeholder="Describe the issue"></textarea><button class="btn btn-dark" type="submit">Open dispute</button></form>`);
FORM.dispute=()=>{closeModal();toast('Dispute opened. BitPromo will reply within 24 hours.');};
ACT.toastMsg=el=>toast(el.dataset.m);

/* ===== MESSAGES ===== */
const THREADS=[
 {id:'t1',role:'biz',w:['c','c1'],order:'BP-24117',unread:1,msgs:[['sys','Order BP-24117 started. ৳10,000 is held by BitPromo payment protection.','Sep 27'],['them','Assalamu alaikum! Thanks for the brief. Should I mention the kacchi combo or the family platter first?','Sep 27, 4:12 PM'],['me','Kacchi combo first please, then the platter. Keep it warm and family-friendly.','Sep 27, 4:20 PM'],['them','Script_v2_BhojKitchen.pdf','Sep 28, 11:02 AM','file'],['me','Script looks perfect. Go ahead!','Sep 28, 11:30 AM'],['them','Draft is uploaded. Have a look!','Oct 02, 6:45 PM','video'],['sys','BitPromo quality check passed: 0:30 duration, logo visible, offer text correct.','Oct 03'],['them','The video is ready for your review. Tell me if you want anything changed.','Oct 03, 10:05 AM']]},
 {id:'t2',role:'biz',w:['c','c7'],order:'BP-24121',msgs:[['sys','Order BP-24121 started. ৳5,500 is held by BitPromo payment protection.','Sep 30'],['them','I’ll come to the Dhanmondi branch on Saturday at 1 PM for the shoot, is that okay?','Oct 01, 2:10 PM'],['me','Yes, the table will be ready. Please try the borhani too!','Oct 01, 2:31 PM'],['them','Perfect, see you then.','Oct 01, 2:33 PM']]},
 {id:'t3',role:'biz',w:['s'],msgs:[['them','Welcome to BitPromo! Your business account is verified. Need help writing your first brief? Just reply here.','Aug 18, 9:00 AM'],['me','Thanks! Can I pay with bKash?','Aug 18, 9:14 AM'],['them','Yes. bKash, Nagad, cards and bank transfer are all supported at checkout.','Aug 18, 9:16 AM']]},
 {id:'t4',role:'creator',w:['b','b1'],order:'BP-24117',msgs:[['sys','New order BP-24117 · ৳10,000 secured by BitPromo. You’ll receive ৳8,000 after approval.','Sep 27'],['me','Assalamu alaikum! Thanks for the brief. Should I mention the kacchi combo or the family platter first?','Sep 27, 4:12 PM'],['them','Kacchi combo first please, then the platter. Keep it warm and family-friendly.','Sep 27, 4:20 PM'],['me','Script_v2_BhojKitchen.pdf','Sep 28, 11:02 AM','file'],['them','Script looks perfect. Go ahead!','Sep 28, 11:30 AM'],['sys','BitPromo quality check passed. Waiting for buyer review.','Oct 03']]},
 {id:'t5',role:'creator',w:['b','b2'],order:'BP-24119',unread:2,msgs:[['sys','New order BP-24119 · ৳15,000 secured by BitPromo.','Sep 28'],['them','We’re sending 6 outfits from the Eid collection on Tuesday. Can you shoot in natural light?','Oct 02, 3:40 PM'],['them','Moodboard_Eid.pdf','Oct 02, 3:41 PM','file']]},
 {id:'t6',role:'creator',w:['s'],msgs:[['them','Your payout of ৳24,000 to bKash was sent successfully.','Sep 30, 10:00 AM'],['them','Tip: creators who reply within 1 hour get 2x more orders.','Oct 01, 9:00 AM']]},
];
function tWho(t){if(t.w[0]==='c'){const c=C(t.w[1]);return{n:c.name,a:av(c,40),s:c.cats[0]};}if(t.w[0]==='b'){const b=B(t.w[1]);return{n:b.name,a:bizAv(b,40),s:b.type};}return{n:'BitPromo Support',a:`<span class="logo-mark" style="width:40px;height:40px;border-radius:12px;flex:none">${ic('play','i-fill')}</span>`,s:'Usually replies in minutes'};}
function bubble(m,t){const[who,txt,time,kind]=m;if(who==='sys')return `<div class="bub sys">${ic('shield')} ${esc(txt)}</div>`;
 let inner=esc(txt);if(kind==='file')inner=`<span class="filechip" style="background:rgba(127,127,127,.14)">${ic('file')}${esc(txt)}</span>`;
 if(kind==='video'){const c=C(t.w[0]==='c'?t.w[1]:'c1');inner=`${esc(txt)}${vt(c,{r:'v',title:'Draft v1',brand:t.w[0]==='c'?'Bhoj Kitchen':B(t.w[1]).name,dur:30})}`;}
 return `<div class="bub ${who==='me'?'me':''}">${inner}<small>${time}</small></div>`;}
function msgUI(role){const list=THREADS.filter(t=>t.role===role);if(!list.length)return `<div class="empty">No conversations yet.</div>`;if(!S.thread||!list.find(t=>t.id===S.thread))S.thread=list[0].id;const t=list.find(x=>x.id===S.thread),w=tWho(t);t.unread=0;
 return `<div class="card msgs"><div class="convs">${list.map(x=>{const ww=tWho(x),last=x.msgs[x.msgs.length-1];return `<button class="conv ${x.id===t.id?'on':''}" data-act="thread" data-id="${x.id}">${ww.a}<div class="grow"><b><span>${esc(ww.n)}</span>${x.unread?`<span class="pill p-acc">${x.unread}</span>`:''}</b><span>${x.order?x.order+' · ':''}${esc(last[1])}</span></div></button>`;}).join('')}</div>
 <div class="thread"><div class="thread-head">${w.a}<div class="grow"><b>${esc(w.n)}</b><div class="small muted">${esc(w.s)}</div></div>${t.order?`<button class="btn btn-ghost btn-sm" data-go="track~${t.order}">${ic('package')}${t.order}</button>`:''}</div>
 <div class="warnbar">${ic('shield')}Keep payments and order communication within BitPromo for transaction protection.</div>
 <div class="thread-body" id="tb">${t.msgs.map(m=>bubble(m,t)).join('')}</div>
 <form class="composer" data-form="msg"><button type="button" class="iconbtn" data-act="attach" aria-label="Attach a file">${ic('clip')}</button><input class="field" name="m" id="msg-input" placeholder="Write a message…" autocomplete="off"><button class="btn btn-pri" type="submit">${ic('send')}</button></form></div></div>`;}
function tbScroll(){const tb=$('#tb');if(tb)tb.scrollTop=tb.scrollHeight;}
function nowT(){return 'Today, '+new Date().toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});}
FORM.msg=f=>{const v=f.m.value.trim();if(!v)return;const t=THREADS.find(x=>x.id===S.thread);t.msgs.push(['me',v,nowT()]);render();$('#msg-input').focus();
 setTimeout(()=>{const rep=t.w[0]==='s'?'Thanks for reaching out! A BitPromo specialist will follow up shortly.':['Got it, I’ll take care of that!','Sounds good. I’ll update you soon.','Thanks! Noted for the next draft.'][t.msgs.length%3];t.msgs.push(['them',rep,nowT()]);if($('#tb')&&S.thread===t.id){$('#tb').insertAdjacentHTML('beforeend',bubble(t.msgs[t.msgs.length-1],t));tbScroll();}},1300);};
ACT.thread=el=>{S.thread=el.dataset.id;render();};
ACT.attach=()=>{const t=THREADS.find(x=>x.id===S.thread);t.msgs.push(['me','Campaign_brief_notes.pdf',nowT(),'file']);render();toast('File shared in this order chat');};
ACT.contact=el=>{const id=el.dataset.id;if(S.role!=='biz')S.role='biz';let t=THREADS.find(x=>x.role==='biz'&&x.w[1]===id);if(!t){t={id:'t'+Date.now(),role:'biz',w:['c',id],msgs:[['sys',`Start a conversation with ${C(id).name}. Keep all payments inside BitPromo.`,'Today']]};THREADS.unshift(t);}S.thread=t.id;go('dash~biz~messages');};

/* ===== DASHBOARDS ===== */
const NAV={biz:[['home','Dashboard','grid'],['discover','Discover Creators','compass'],['orders','My Orders','package'],['messages','Messages','message'],['favorites','Favorites','heart'],['campaigns','Campaigns','megaphone'],['payments','Payments','wallet'],['reviews','Reviews','star'],['settings','Settings','sliders']],
 creator:[['home','Dashboard','grid'],['services','My Services','video'],['orders','Orders','package'],['messages','Messages','message'],['earnings','Earnings','wallet'],['portfolio','Portfolio','film'],['reviews','Reviews','star'],['availability','Availability','calendar'],['verification','Verification','badge'],['settings','Settings','sliders']],
 admin:[['overview','Overview','grid'],['users','Users','users'],['creators','Creators','film'],['businesses','Businesses','building'],['orders','Orders','package'],['payments','Payments','wallet'],['commission','Commission','chart'],['verification','Verification','badge'],['disputes','Disputes','scale'],['reviews','Reviews','star'],['campaigns','Campaigns','megaphone'],['reports','Reports','trend'],['settings','Settings','sliders']]};
const DASH={biz:{},creator:{},admin:{}};
PAGES.dash=(role,sec)=>{const r=USERS[role]?role:'biz';const nav=NAV[r];const cur=DASH[r][sec]?sec:nav[0][0];const badge={messages:THREADS.filter(t=>t.role===r).reduce((s,t)=>s+(t.unread||0),0),verification:r==='admin'?S.vq.filter(v=>v.st==='Pending').length:0,disputes:r==='admin'?S.disp.filter(d=>d.st==='Open').length:0,orders:r==='creator'?ORDERS.filter(o=>o.c===ME_CRE&&o.st===1).length:0};
 const to=k=>k==='discover'?'explore':`dash~${r}~${k}`;
 return `<div class="dash"><aside class="side" aria-label="Dashboard"><div class="who">${userAv(40)}<div><b>${USERS[r].name}</b><small>${USERS[r].label} account · demo</small></div></div>${nav.map(([k,l,i])=>`<button class="sl ${k===cur?'on':''}" data-go="${to(k)}">${ic(i)}${l}${badge[k]?`<span class="cnt">${badge[k]}</span>`:''}</button>`).join('')}
 <div style="margin-top:auto;padding-top:16px;border-top:1px solid var(--line)"><span class="small muted" style="padding:0 12px">Switch demo account</span>${Object.keys(USERS).filter(k=>k!==r).map(k=>`<button class="sl" data-act="signinAs" data-r="${k}">${ic('refresh')}${USERS[k].label}</button>`).join('')}<button class="sl" data-act="signout">${ic('logout')}Sign out</button></div></aside>
 <div style="min-width:0"><div class="mobile-tabs">${nav.map(([k,l])=>`<button class="chipt ${k===cur?'on':''}" data-go="${to(k)}">${l}</button>`).join('')}</div><div class="dmain">${DASH[r][cur]()}</div></div></div>`;};
POST.dash=()=>tbScroll();
const greet=()=>{const h=new Date().getHours();return h<12?'Good morning':h<17?'Good afternoon':'Good evening';};
const stat=(l,v,i,d)=>`<div class="card stat"><small>${ic(i)}${l}</small><b>${v}</b>${d?`<span class="d">${d}</span>`:''}</div>`;
const dhead=(t,s,actions='')=>`<div class="row between" style="margin-bottom:22px;align-items:flex-end"><div><h1 style="font-size:clamp(24px,2.6vw,30px)">${t}</h1>${s?`<p class="muted" style="margin-top:6px">${s}</p>`:''}</div><div class="row">${actions}</div></div>`;
const OCOLS=[['Order'],['Creator'],['Status'],['Due'],['Amount','num']];
// business
DASH.biz.home=()=>{const mine=ORDERS.filter(o=>o.b===ME_BIZ),act=mine.filter(o=>o.st<7),done=mine.filter(o=>o.st===7),held=act.reduce((s,o)=>s+amt(o),0),spend=mine.reduce((s,o)=>s+amt(o),0)+112000,rv=mine.find(o=>o.st===6);
 return dhead(`${greet()}, Bhoj Kitchen`,'Here’s what’s happening with your promotional videos.',`<button class="btn btn-ghost" data-act="postCamp">${ic('megaphone')}Post a campaign</button><button class="btn btn-pri" data-go="explore">${ic('search')}Find a creator</button>`)+
 (rv?`<div class="card pad row between" style="margin-bottom:20px;border-color:transparent;background:var(--warn-soft)"><div class="row">${av(C(rv.c),44)}<div><b>${esc(C(rv.c).name)} delivered “${esc(rv.title)}”</b><div class="small" style="color:var(--warn)">Passed quality check. Approve it to release payment.</div></div></div><button class="btn btn-dark btn-sm" data-go="track~${rv.id}">Review video</button></div>`:'')+
 `<div class="stats">${stat('Active campaigns',S.myCamps.length,'megaphone','12 proposals received')}${stat('Pending orders',act.length,'package',`${tk(held)} protected`)}${stat('Completed campaigns',done.length+9,'check')}${stat('Total spending',tk(spend),'wallet','Since Jan 2026')}</div>
 <div class="dash-2" style="margin-top:20px"><div class="card" style="min-width:0"><div class="row between pad" style="padding-bottom:4px"><h3>Recent orders</h3><button class="btn-link" data-go="dash~biz~orders">View all</button></div>${table(OCOLS,orderRows(mine.slice(0,6),'biz'))}</div>
 <div class="stack" style="gap:20px"><div class="card pad"><h3>Payment protection</h3><p class="muted small" style="margin-top:4px">Held by BitPromo for your ${act.length} active orders</p><div class="pkg-price" style="font-size:30px;margin:8px 0">${tk(held)}</div><p class="small muted">Released to creators only after you approve each video.</p></div>
 <div class="card pad"><h3 style="margin-bottom:12px">Recommended for Bhoj Kitchen</h3><div class="stack">${['c19','c13','c20'].map(C).map(c=>`<div class="row" style="flex-wrap:nowrap">${av(c,40)}<div class="grow"><b style="font-size:14px">${esc(c.name)}</b><div class="small muted">${c.cats[0]} · from ${tk(c.price)}</div></div><button class="btn btn-ghost btn-sm" data-go="creator~${c.id}">View</button></div>`).join('')}</div></div></div></div>`;};
DASH.biz.orders=()=>{const mine=ORDERS.filter(o=>o.b===ME_BIZ),tab=S.otab||'all',list=mine.filter(o=>tab==='all'||(tab==='active'?o.st<7:o.st===7));return dhead('My orders','Every order is protected until you approve the video.',`<button class="btn btn-pri" data-go="explore">New order</button>`)+`<div class="tabs">${[['all','All',mine.length],['active','Active',mine.filter(o=>o.st<7).length],['done','Completed',mine.filter(o=>o.st===7).length]].map(([k,l,n])=>`<button class="${tab===k?'on':''}" data-act="otab" data-k="${k}">${l} (${n})</button>`).join('')}</div><div class="card">${table(OCOLS,orderRows(list,'biz'))}</div>`;};
ACT.otab=el=>{S.otab=el.dataset.k;render();};
DASH.biz.messages=()=>dhead('Messages','Talk to creators and BitPromo support about your orders.')+msgUI('biz');
DASH.biz.favorites=()=>{const f=CREATORS.filter(c=>S.favs.has(c.id));return dhead('Favorites',`${f.length} saved creators`)+(f.length?`<div class="grid g3">${f.map(creatorCard).join('')}</div>`:`<div class="empty">Tap the heart on any creator to save them here.<br><br><button class="btn btn-pri btn-sm" data-go="explore">Explore creators</button></div>`);};
DASH.biz.campaigns=()=>{const mine=CAMPAIGNS.filter(k=>S.myCamps.includes(k.id));const props=[['c7',14000,'I can shoot at your Dhanmondi branch during Friday lunch rush, with a taste-test reaction.'],['c1',15000,'Warm family-style story: a mother booking a table for the family. Includes script.'],['c19',12000,'Aesthetic close-ups of the platter with a quick Reel cut for Instagram.']];
 return dhead('Campaigns','Post a brief with a budget and let verified creators apply.',`<button class="btn btn-pri" data-act="postCamp">${ic('plus')}Post a campaign</button>`)+`<div class="grid g2">${mine.map(campCard).join('')}</div>
 <div class="card" style="margin-top:22px"><div class="pad" style="padding-bottom:4px"><h3>Proposals for “Looking for a Food Creator”</h3><p class="small muted">${props.length} shortlisted of 12 applications</p></div>${props.map(([id,p,m])=>{const c=C(id);return `<div class="row pad" style="border-top:1px solid var(--line);flex-wrap:nowrap;align-items:flex-start">${av(c,44)}<div class="grow"><div class="row between"><b>${esc(c.name)} ${vb()}</b><b class="tnum">${tk(p)}</b></div><div class="small muted">${rating(c.rating,c.revs)} · ${c.city}</div><p style="margin-top:6px;color:var(--ink-2)">${m}</p><div class="row" style="margin-top:10px"><button class="btn btn-pri btn-sm" data-go="order~${id}~1">Hire ${first(c)}</button><button class="btn btn-ghost btn-sm" data-go="creator~${id}">View profile</button></div></div></div>`;}).join('')}</div>`;};
DASH.biz.payments=()=>{const mine=ORDERS.filter(o=>o.b===ME_BIZ);const meth=['bKash','bKash','Nagad','Card','bKash','Bank transfer','bKash'];return dhead('Payments','Your payments are held by BitPromo until you approve each video.')+
 `<div class="stats" style="margin-bottom:20px">${stat('Held in protection',tk(mine.filter(o=>o.st<7).reduce((s,o)=>s+amt(o),0)),'lock')}${stat('Released to creators',tk(mine.filter(o=>o.st===7).reduce((s,o)=>s+amt(o),0)),'check')}${stat('Refunds','৳0','refresh')}</div>
 <div class="dash-2"><div class="card">${table([['Date'],['Order'],['Creator'],['Method'],['Amount','num'],['Status']],mine.map((o,i)=>({go:`track~${o.id}`,cells:[o.created,`<b class="tnum">${o.id}</b>`,esc(C(o.c).name),o.paid||meth[i%meth.length],`<b>${tk(amt(o))}</b>`,o.st===7?'<span class="pill p-good">Released to creator</span>':'<span class="pill p-acc">Held by BitPromo</span>']})))}</div>
 <div class="card pad stack"><h3>Payment methods</h3>${[['bKash','•••• 4421 · Default','#E2136E'],['Visa','•••• 1028 · Exp 08/28','#1F2A44']].map(([n,d,c])=>`<div class="row" style="padding:12px;border:1px solid var(--line);border-radius:10px;flex-wrap:nowrap"><span class="paym"><span class="lg" style="background:${c};width:42px;height:28px;display:grid;place-items:center;border-radius:6px;color:#fff;font-size:10px;font-weight:800">${n.slice(0,2).toUpperCase()}</span></span><div class="grow"><b>${n}</b><div class="small muted">${d}</div></div></div>`).join('')}<button class="btn btn-ghost btn-sm" data-act="toastMsg" data-m="Payment methods connect in the live product">${ic('plus')}Add method</button><p class="small muted">Shown for design. No payment provider is connected in this prototype.</p></div></div>`;};
DASH.biz.reviews=()=>dhead('Reviews','Reputation works both ways on BitPromo.')+`<div class="dash-2"><div class="card pad"><h3>Reviews you’ve given</h3>${REVIEWS.filter(r=>r.b===ME_BIZ).map(r=>{const c=C(r.c);return `<div class="review">${av(c,40)}<div class="grow"><div class="row between"><b>${esc(c.name)}</b><span class="small muted">${r.date}</span></div><div class="stars">${stars(r.stars)}</div><p style="margin-top:6px">${esc(r.text)}</p></div></div>`;}).join('')}</div>
 <div class="card pad"><h3>What creators say about you</h3><div class="row" style="margin:10px 0"><span class="pkg-price" style="font-size:30px">5.0</span><span class="stars">★★★★★</span><span class="small muted">as a buyer · 2 reviews</span></div>${CREATOR_REVIEWS.map(r=>{const c=C(r.by);return `<div class="review">${av(c,40)}<div class="grow"><b>${esc(c.name)}</b><div class="stars">${stars(r.stars)}</div><p style="margin-top:6px">${esc(r.text)}</p></div></div>`;}).join('')}</div></div>`;
DASH.biz.settings=()=>dhead('Settings','Business profile and notifications.')+`<div class="dash-2"><form class="card pad form" data-form="saved"><div class="full"><h3>Business profile</h3></div>${[['Business name','Bhoj Kitchen'],['Business type','Restaurant'],['Website','bhojkitchen.com.bd'],['City','Dhaka'],['Contact email','business@bitpromo.demo'],['Phone','+880 1711-000000']].map(([l,v],i)=>`<div><label for="bs-${i}">${l}</label><input class="field" id="bs-${i}" value="${v}"></div>`).join('')}<div class="full"><button class="btn btn-pri" type="submit">Save changes</button></div></form>
 <div class="stack" style="gap:20px"><div class="card pad"><h3>Verification</h3><div class="protect" style="margin-top:10px">${ic('badge')}<span>Business verified · Trade licence checked on Aug 18, 2026</span></div></div><div class="card pad stack"><h3>Notifications</h3>${['Order updates','New proposals on my campaigns','Messages from creators','Weekly creator recommendations'].map((n,i)=>`<div class="row between"><span>${n}</span><button class="switch ${i<3?'on':''}" data-act="sw" aria-label="${n}"></button></div>`).join('')}</div></div></div>`;
FORM.saved=()=>toast('Changes saved');ACT.sw=el=>{el.classList.toggle('on');toast(el.classList.contains('on')?'Turned on':'Turned off');};
// creator
const creMine=()=>ORDERS.filter(o=>o.c===ME_CRE);
DASH.creator.home=()=>{const mine=creMine(),act=mine.filter(o=>o.st<7),pend=act.reduce((s,o)=>s+amt(o)*.8,0),req=mine.filter(o=>o.st===1);
 return dhead(`${greet()}, Ayesha`,'Your orders, earnings and profile at a glance.',`<button class="btn btn-ghost" data-go="creator~c1">${ic('eye')}View public profile</button><button class="btn btn-pri" data-go="campaigns">${ic('megaphone')}Find campaigns</button>`)+
 req.map(o=>`<div class="card pad row between" style="margin-bottom:16px;background:var(--accent-soft);border-color:transparent"><div class="row">${bizAv(B(o.b),44)}<div><b>New order request from ${esc(B(o.b).name)}</b><div class="small muted">${esc(o.title)} · ${pkgs(C(o.c))[o.pkg].n} · you earn ${tk(amt(o)*.8)}</div></div></div><div class="row"><button class="btn btn-good btn-sm" data-act="accept" data-id="${o.id}">Accept</button><button class="btn btn-ghost btn-sm" data-go="track~${o.id}">View brief</button></div></div>`).join('')+
 `<div class="stats">${stat('Total earnings',tk(1048000),'wallet','+18% vs last month')}${stat('Pending earnings',tk(pend),'clock','Released after approval')}${stat('Completed orders',127,'check')}${stat('Active orders',act.length,'package')}${stat('Average rating','4.9 ★','star','112 reviews')}${stat('Profile views','3,482','eye','This month')}</div>
 <div class="dash-2" style="margin-top:20px"><div class="stack" style="gap:20px;min-width:0"><div class="card pad"><div class="row between"><h3>Net earnings</h3><span class="small muted">Last 6 months, after 20% commission</span></div>${barChart(EARN,{fmt:v=>'৳'+v+'K',label:'Net earnings by month'})}</div>
 <div class="card" style="min-width:0"><div class="row between pad" style="padding-bottom:4px"><h3>Recent orders</h3><button class="btn-link" data-go="dash~creator~orders">View all</button></div>${table([['Order'],['Business'],['Status'],['Due'],['You earn','num']],orderRows(mine.slice(0,5),'creator'))}</div></div>
 <div class="stack" style="gap:20px"><div class="card pad stack"><h3>How your earnings work</h3><p class="small muted">Latest order BP-24117 · Standard package</p><div class="grid" style="grid-template-columns:1fr 1fr 1fr;gap:8px;text-align:center">${[['Order value','৳10,000','var(--ink)'],['BitPromo 20%','−৳2,000','var(--accent)'],['You receive','৳8,000','var(--good)']].map(([l,v,c])=>`<div style="padding:10px 4px;background:var(--bg-2);border-radius:10px"><div class="small muted">${l}</div><b class="tnum" style="color:${c};font-size:17px">${v}</b></div>`).join('')}</div>${splitBar(10000)}<button class="btn btn-ghost btn-sm" data-go="dash~creator~earnings">See all earnings</button></div>
 <div class="card pad stack"><div class="row between"><div><h3>Accepting orders</h3><p class="small muted">${S.avail?'Your profile shows “Available”':'Your profile shows “Fully booked”'}</p></div><button class="switch ${S.avail?'on':''}" data-act="avail" aria-label="Accepting orders"></button></div></div>
 <div class="card pad"><div class="protect">${ic('badge')}<span>Verified Creator since Aug 2025. Your badge shows on every listing.</span></div></div></div></div>`;};
ACT.avail=()=>{S.avail=!S.avail;C(ME_CRE).avail=S.avail;toast(S.avail?'You are accepting new orders':'Profile set to fully booked');render();};
DASH.creator.orders=()=>{const mine=creMine();return dhead('Orders','Accept new requests, upload drafts and track approvals.')+`<div class="card">${table([['Order'],['Business'],['Status'],['Due'],['You earn','num']],orderRows(mine,'creator'))}</div>`;};
DASH.creator.messages=()=>dhead('Messages','Chat with businesses about their orders.')+msgUI('creator');
DASH.creator.services=()=>{const c=C(ME_CRE),P=pkgs(c);return dhead('My services','Set your packages. Buyers see these prices on your profile.',`<button class="btn btn-pri" data-act="toastMsg" data-m="Packages saved">Save packages</button>`)+
 `<div class="grid g3">${P.map((p,i)=>`<div class="card pad stack"><div class="row between"><h3>${p.n}</h3><span class="tag">${p.dur} sec</span></div><div><label class="small" style="font-weight:650" for="sv-${i}">Price (৳)</label><input class="field tnum" type="number" id="sv-${i}" data-svc="${i}" value="${p.price}" min="500" step="500"></div><div class="sumrow small"><span class="muted">BitPromo commission (20%)</span><span class="tnum" id="svc-${i}-c">−${tk(p.price*.2)}</span></div><div class="sumrow"><b>You receive</b><b class="tnum" style="color:var(--good)" id="svc-${i}-n">${tk(p.price*.8)}</b></div><div class="small muted">${p.days}-day delivery · ${p.rev} revision${p.rev>1?'s':''}</div><ul class="checks small">${FEATS.map(([k,l])=>`<li class="${p.f[k]?'':'no'}">${ic(p.f[k]?'check':'x')}${l}</li>`).join('')}</ul></div>`).join('')}</div>
 <div class="card" style="margin-top:20px"><div class="pad" style="padding-bottom:4px"><h3>Listed services</h3></div>${table([['Service'],['Platform'],['Price','num'],['Delivery']],SERVICES.filter(s=>s.c===ME_CRE).map(s=>({go:`creator~${s.c}~${s.pkg}`,cells:[`<b>${esc(s.title)}</b>`,s.plat,tk(s.price),`${s.days} days`]})))}</div>`;};
document.addEventListener('input',e=>{const i=e.target.dataset&&e.target.dataset.svc;if(i==null)return;const v=+e.target.value||0;$(`#svc-${i}-c`).textContent='−'+tk(v*.2);$(`#svc-${i}-n`).textContent=tk(v*.8);});
DASH.creator.earnings=()=>{const mine=creMine(),pend=mine.filter(o=>o.st<7).reduce((s,o)=>s+amt(o)*.8,0);
 return dhead('Earnings','BitPromo keeps a flat 20% commission. Everything else is yours.',`<button class="btn btn-pri" data-act="withdraw">${ic('wallet')}Withdraw</button>`)+
 `<div class="stats">${stat('Available balance',tk(S.bal.avail),'wallet')}${stat('Pending balance',tk(pend),'clock','From active orders')}${stat('Total earnings',tk(1048000),'trend')}${stat('Withdrawable balance',tk(S.bal.avail),'check','Ready now')}</div>
 <div class="dash-2" style="margin-top:20px"><div class="card pad stack" style="gap:18px"><h3>Commission breakdown</h3><div class="grid g3" style="gap:12px">${[['Order value','৳10,000','Paid by the business'],['BitPromo commission','৳2,000','20% of the order'],['Your earnings','৳8,000','Paid out to you']].map(([l,v,s],i)=>`<div style="padding:16px;border:1px solid var(--line);border-radius:12px"><div class="small muted" style="font-weight:650">${l}</div><div class="pkg-price" style="font-size:26px;color:${['var(--ink)','var(--accent)','var(--good)'][i]}">${v}</div><div class="small muted">${s}</div></div>`).join('')}</div>${splitBar(10000)}</div>
 <div class="card pad"><h3>Earnings by month</h3>${barChart(EARN,{fmt:v=>'৳'+v+'K',w:400,h:230,label:'Earnings by month'})}</div></div>
 <div class="card" style="margin-top:20px"><div class="pad" style="padding-bottom:4px"><h3>Transactions</h3></div>${table([['Order'],['Business'],['Order value','num'],['Commission (20%)','num'],['Your earnings','num'],['Status']],mine.map(o=>({go:`track~${o.id}`,cells:[`<b class="tnum">${o.id}</b>`,esc(B(o.b).name),tk(amt(o)),`−${tk(amt(o)*.2)}`,`<b style="color:var(--good)">${tk(amt(o)*.8)}</b>`,o.st===7?'<span class="pill p-good">Paid</span>':'<span class="pill p-warn">Pending approval</span>']})))}</div>
 ${S.bal.withdrawn.length?`<div class="card" style="margin-top:20px"><div class="pad" style="padding-bottom:4px"><h3>Withdrawals</h3></div>${table([['Date'],['Method'],['Amount','num'],['Status']],S.bal.withdrawn.map(w=>({cells:['Oct 03',w.m,tk(w.a),'<span class="pill p-acc">Processing</span>']})))}</div>`:''}`;};
ACT.withdraw=()=>modal(`${mhead('Withdraw earnings')}<form class="modal-body" data-form="withdraw"><div class="sumrow"><span class="muted">Available</span><b>${tk(S.bal.avail)}</b></div><div><label class="small" style="font-weight:650" for="wd-a">Amount (৳)</label><input class="field" type="number" id="wd-a" name="a" value="${S.bal.avail}" max="${S.bal.avail}" min="500"></div><div><label class="small" style="font-weight:650" for="wd-m">Send to</label><select class="field" id="wd-m" name="m"><option>bKash · 01711-•••421</option><option>Nagad · 01819-•••118</option><option>Bank · DBBL ••••2290</option></select></div><div class="demo-note">${ic('alert')}Simulated. No money moves in this prototype.</div><button class="btn btn-pri" type="submit">Withdraw</button></form>`);
FORM.withdraw=f=>{const a=Math.min(+f.a.value||0,S.bal.avail);if(a<=0){toast('Enter an amount');return;}S.bal.avail-=a;S.bal.withdrawn.unshift({a,m:f.m.value.split(' ·')[0]});closeModal();toast(`${tk(a)} withdrawal requested`);render();};
DASH.creator.portfolio=()=>{const c=C(ME_CRE);const t=['Restaurant promo','Product review','Eid campaign','Brand intro','Instagram Reel','Testimonial','Fintech explainer','Admission promo','Skincare review','Mega sale'];return dhead('Portfolio','Your best work. Buyers watch these before ordering.',`<button class="btn btn-pri" data-act="addPort">${ic('upload')}Upload video</button>`)+`<div class="grid g4 keep2">${Array.from({length:S.portfolio},(_,i)=>vt(c,{r:'v',title:t[i%t.length],i,dur:[15,30,60][i%3]})).join('')}</div>`;};
ACT.addPort=()=>{S.portfolio++;toast('Video added to your portfolio');render();};
DASH.creator.reviews=()=>dhead('Reviews','What businesses say about you, and what you said about them.')+`<div class="dash-2"><div class="card pad"><div class="row"><span class="pkg-price" style="font-size:34px">4.9</span><span class="stars">★★★★★</span><span class="small muted">112 reviews</span></div>${REVIEWS.filter(r=>r.c===ME_CRE).map(reviewItem).join('')}</div><div class="card pad"><h3>Reviews you’ve given</h3>${CREATOR_REVIEWS.map(r=>reviewItem({...r,date:''})).join('')}</div></div>`;
DASH.creator.availability=()=>{const days=Array.from({length:14},(_,i)=>{const d=new Date(2026,9,4+i);return{d,b:[1,2,5,8,9,12].includes(i)};});return dhead('Availability','Control when buyers can order from you.')+
 `<div class="dash-2"><div class="card pad stack"><div class="row between"><div><h3>Accepting new orders</h3><p class="small muted">Turn off to show “Fully booked” on your profile.</p></div><button class="switch ${S.avail?'on':''}" data-act="avail" aria-label="Accepting new orders"></button></div>
 <div><label class="small" style="font-weight:650" for="cap">Max active orders at a time</label><select class="field" id="cap"><option>3</option><option selected>5</option><option>8</option></select></div>
 <h3 style="margin-top:8px">Next 14 days</h3><div class="grid" style="grid-template-columns:repeat(7,1fr);gap:6px">${days.map(x=>`<div style="padding:10px 4px;border-radius:10px;text-align:center;background:${x.b?'var(--accent-soft)':'var(--bg-2)'};color:${x.b?'var(--accent)':'var(--ink)'}"><div class="small">${x.d.toLocaleDateString('en-GB',{weekday:'short'})}</div><b>${x.d.getDate()}</b><div style="font-size:10.5px">${x.b?'Shoot':'Free'}</div></div>`).join('')}</div></div>
 <div class="card pad stack"><h3>Time off</h3><p class="small muted">Going away? Buyers can still message you, but can’t place orders.</p><div class="form"><div><label for="v1">From</label><input type="date" class="field" id="v1" value="2026-10-20"></div><div><label for="v2">To</label><input type="date" class="field" id="v2" value="2026-10-24"></div></div><button class="btn btn-ghost btn-sm" style="align-self:flex-start" data-act="toastMsg" data-m="Time off scheduled">Schedule time off</button></div></div>`;};
DASH.creator.verification=()=>dhead('Verification','Your verified status and the checks behind it.')+`<div class="card pad stack" style="gap:20px"><div class="row"><span class="verified-chip" style="font-size:15px;padding:6px 14px 6px 8px">${vb()}Verified Creator ✓</span><span class="small muted">Since Aug 2025</span></div>${vsteps(7)}<div class="grid g3">${[['id','Identity documents','National ID checked by BitPromo'],['globe','Social profiles','Facebook, Instagram and YouTube ownership confirmed'],['film','Portfolio review','6 videos reviewed for quality']].map(([i,h,p])=>`<div class="feat"><span class="fi">${ic(i)}</span><div><h4>${h}</h4><p class="small muted">${p}</p></div></div>`).join('')}</div><p class="small muted">Verification is a platform status. It confirms these steps were completed. It is not an endorsement of the creator’s reputation.</p></div>`;
DASH.creator.settings=()=>{const c=C(ME_CRE);return dhead('Profile settings','This is what buyers see on your public profile.',`<button class="btn btn-ghost" data-go="creator~c1">${ic('eye')}Preview profile</button>`)+`<form class="card pad form" data-form="saved"><div><label for="cs-n">Display name</label><input class="field" id="cs-n" value="${c.name}"></div><div><label for="cs-c">City</label><input class="field" id="cs-c" value="${c.city}"></div><div class="full"><label for="cs-b">Bio</label><textarea class="field" id="cs-b">${c.tag}</textarea></div><div><label for="cs-l">Languages</label><input class="field" id="cs-l" value="${c.langs.join(', ')}"></div><div><label for="cs-k">Categories</label><input class="field" id="cs-k" value="${c.cats.join(', ')}"></div>${['Facebook','Instagram','YouTube','TikTok'].map(p=>`<div><label for="cs-${p}">${p}</label><input class="field" id="cs-${p}" value="${p.toLowerCase()}.com/ayesharahman.demo"></div>`).join('')}<div class="full"><button class="btn btn-pri" type="submit">Save profile</button></div></form>`;};
// admin
const GMV_TOTAL=GMV.reduce((s,g)=>s+g[1],0)*100000;
DASH.admin.overview=()=>{const pendV=S.vq.filter(v=>v.st==='Pending'),openD=S.disp.filter(d=>d.st==='Open');return dhead('Marketplace overview','BitPromo operations · Apr–Sep 2026',`<button class="btn btn-ghost" data-go="dash~admin~reports">${ic('chart')}Reports</button>`)+
 `<div class="stats">${stat('Total GMV',tk(GMV_TOTAL),'trend','+25% month on month')}${stat('BitPromo revenue',tk(GMV_TOTAL*.2),'wallet','20% commission')}${stat('Active creators','186','film')}${stat('Active businesses','412','building')}${stat('Completed orders','742','check')}${stat('Pending verification',pendV.length,'badge')}${stat('Open disputes',openD.length,'scale')}</div>
 <div class="dash-2" style="margin-top:20px"><div class="card pad"><div class="row between"><h3>Gross merchandise value</h3><span class="small muted">৳ lakh per month</span></div>${barChart(GMV,{fmt:v=>v+'L',label:'GMV by month in lakh taka'})}</div>
 <div class="card pad stack"><div class="row between"><h3>Verification queue</h3><button class="btn-link" data-go="dash~admin~verification">All</button></div>${pendV.slice(0,3).map(v=>`<div class="row" style="flex-wrap:nowrap">${av(v,38)}<div class="grow"><b style="font-size:14px">${v.name}</b><div class="small muted">${v.cat} · ${v.followers}</div></div><button class="btn btn-good btn-sm" data-act="vq" data-n="${v.name}" data-ok="1">Approve</button></div>`).join('')||'<p class="muted small">Queue is clear.</p>'}</div></div>
 <div class="card" style="margin-top:20px"><div class="row between pad" style="padding-bottom:4px"><h3>Latest orders</h3><button class="btn-link" data-go="dash~admin~orders">All orders</button></div>${adminOrders(ORDERS.slice(0,6))}</div>`;};
function adminOrders(list){return table([['Order'],['Business'],['Creator'],['Status'],['Value','num'],['Commission','num']],list.map(o=>({go:`track~${o.id}`,cells:[`<b class="tnum">${o.id}</b>`,esc(B(o.b).name),esc(C(o.c).name),stagePill(o.st),tk(amt(o)),`<b style="color:var(--accent)">${tk(amt(o)*.2)}</b>`]})));}
DASH.admin.users=()=>dhead('Users',`${CREATORS.length+BUSINESSES.length} demo accounts`)+`<div class="card">${table([['Name'],['Type'],['City'],['Joined'],['Status']],[...CREATORS.map((c,i)=>({go:`creator~${c.id}`,cells:[`<div class="who-cell">${av(c,32)}${esc(c.name)}</div>`,'Creator',c.city,['Aug 2025','Sep 2025','Jan 2026','Mar 2026'][i%4],'<span class="pill p-good">Verified</span>']})),...BUSINESSES.map((b,i)=>({cells:[`<div class="who-cell">${bizAv(b,32)}${esc(b.name)}</div>`,'Business',b.city,['Feb 2026','Apr 2026','Jun 2026'][i%3],i%5===4?'<span class="pill p-warn">Docs pending</span>':'<span class="pill p-good">Verified</span>']}))])}</div>`;
DASH.admin.creators=()=>dhead('Creators','Verified sellers on the marketplace.')+`<div class="card">${table([['Creator'],['Category'],['City'],['Rating','num'],['Orders','num'],['Starting price','num'],['Status']],CREATORS.map(c=>({go:`creator~${c.id}`,cells:[`<div class="who-cell">${av(c,32)}<b>${esc(c.name)}</b></div>`,c.cats[0],c.city,c.rating.toFixed(1),c.orders,tk(c.price),c.avail?'<span class="pill p-good">Active</span>':'<span class="pill p-mute">Booked</span>']})))}</div>`;
DASH.admin.businesses=()=>dhead('Businesses','Buyers on the marketplace.')+`<div class="card">${table([['Business'],['Type'],['City'],['Orders','num'],['Spend','num']],BUSINESSES.map(b=>{const os=ORDERS.filter(o=>o.b===b.id);return{cells:[`<div class="who-cell">${bizAv(b,32)}<b>${esc(b.name)}</b></div>`,b.type,b.city,os.length,tk(os.reduce((s,o)=>s+amt(o),0))]};}))}</div>`;
DASH.admin.orders=()=>dhead('Orders',`${ORDERS.length} orders`)+`<div class="card">${adminOrders(ORDERS)}</div>`;
DASH.admin.payments=()=>{const held=ORDERS.filter(o=>o.st<7).reduce((s,o)=>s+amt(o),0),rel=ORDERS.filter(o=>o.st===7).reduce((s,o)=>s+amt(o),0);return dhead('Payments','Money in protection, released and refunded.')+`<div class="stats" style="margin-bottom:20px">${stat('Held in protection',tk(held),'lock')}${stat('Released (demo orders)',tk(rel),'check')}${stat('Paid to creators',tk(rel*.8),'wallet')}${stat('Refunded','৳16,000','refresh','1 dispute')}</div><div class="card">${table([['Order'],['Business'],['Amount','num'],['Status']],ORDERS.map(o=>({go:`track~${o.id}`,cells:[`<b class="tnum">${o.id}</b>`,esc(B(o.b).name),tk(amt(o)),o.st===7?'<span class="pill p-good">Released</span>':'<span class="pill p-acc">Held</span>']})))}</div>`;};
DASH.admin.commission=()=>{const done=ORDERS.filter(o=>o.st===7),g=done.reduce((s,o)=>s+amt(o),0);return dhead('Commission','A flat 20% on every completed order.')+`<div class="dash-2"><div class="card">${table([['Order'],['Order value','num'],['BitPromo 20%','num'],['Creator 80%','num']],done.map(o=>({go:`track~${o.id}`,cells:[`<b class="tnum">${o.id}</b>`,tk(amt(o)),`<b style="color:var(--accent)">${tk(amt(o)*.2)}</b>`,tk(amt(o)*.8)]})).concat([{cells:['<b>Total</b>',`<b>${tk(g)}</b>`,`<b style="color:var(--accent)">${tk(g*.2)}</b>`,`<b>${tk(g*.8)}</b>`]}]))}</div>
 <div class="card pad stack"><h3>Example</h3><div class="sumrow"><span>Creator service price</span><b>৳20,000</b></div><div class="sumrow"><span>BitPromo</span><b style="color:var(--accent)">৳4,000</b></div><div class="sumrow"><span>Creator</span><b style="color:var(--good)">৳16,000</b></div>${splitBar(20000)}<h4 style="margin-top:10px">Future revenue options</h4><ul class="checks small">${['Featured creator placement','Sponsored listings','Business subscriptions','Campaign management fees','Premium verification','Agency and enterprise accounts'].map(x=>`<li class="no">${ic('plus')}${x}</li>`).join('')}</ul></div></div>`;};
DASH.admin.verification=()=>dhead('Creator verification','Review identity, social profiles and portfolio before approving.')+`<div class="grid g2">${S.vq.map(v=>`<div class="card pad stack"><div class="row">${av(v,52)}<div class="grow"><b>${v.name}</b><div class="small muted">${v.cat} · ${v.city} · ${v.followers} followers</div></div>${v.st==='Pending'?'<span class="pill p-warn">Pending</span>':v.st==='Approved'?'<span class="pill p-good">Approved</span>':'<span class="pill p-bad">Rejected</span>'}</div><div class="row" style="gap:6px">${['NID_front.jpg','NID_back.jpg','Selfie.jpg','3 social links','4 portfolio videos'].map(f=>`<span class="filechip">${ic('check')}${f}</span>`).join('')}</div><div class="small muted">Submitted ${v.submitted}</div>${v.st==='Pending'?`<div class="row"><button class="btn btn-good btn-sm" data-act="vq" data-n="${v.name}" data-ok="1">Approve</button><button class="btn btn-ghost btn-sm" data-act="vq" data-n="${v.name}" data-ok="0">Reject</button></div>`:''}</div>`).join('')}</div>`;
ACT.vq=el=>{const v=S.vq.find(x=>x.name===el.dataset.n);v.st=el.dataset.ok==='1'?'Approved':'Rejected';toast(`${v.name} ${v.st.toLowerCase()}`);render();};
DASH.admin.disputes=()=>dhead('Disputes','Every decision is based on the order brief, messages and files.')+`<div class="stack">${S.disp.map(d=>`<div class="card pad stack"><div class="row between"><div class="row"><b class="tnum">${d.id}</b><span class="small muted">Order ${d.order}</span></div>${d.st==='Open'?'<span class="pill p-warn">Open</span>':`<span class="pill p-good">${d.st}</span>`}</div><p>${d.reason}</p><div class="row small muted" style="gap:16px"><span>Business: <b style="color:var(--ink)">${B(d.b).name}</b></span><span>Creator: <b style="color:var(--ink)">${C(d.c).name}</b></span><span>Amount: <b style="color:var(--ink)">${tk(d.amt)}</b></span></div>${d.st==='Open'?`<div class="row"><button class="btn btn-ghost btn-sm" data-act="resolve" data-id="${d.id}" data-r="Refunded to buyer">Refund buyer</button><button class="btn btn-ghost btn-sm" data-act="resolve" data-id="${d.id}" data-r="Released to creator">Release to creator</button><button class="btn btn-dark btn-sm" data-act="resolve" data-id="${d.id}" data-r="Split 50/50">Split 50/50</button></div>`:''}</div>`).join('')}</div>`;
ACT.resolve=el=>{const d=S.disp.find(x=>x.id===el.dataset.id);d.st=el.dataset.r;toast(`${d.id}: ${d.st}`);render();};
DASH.admin.reviews=()=>dhead('Review moderation','Hide reviews that break community guidelines.')+`<div class="card pad">${REVIEWS.map((r,i)=>{const b=B(r.b),c=C(r.c),h=S.reviewsHidden.has(i);return `<div class="review" style="${h?'opacity:.45':''}">${bizAv(b)}<div class="grow"><div class="row between"><b>${esc(b.name)} → ${esc(c.name)}</b><span class="stars">${stars(r.stars)}</span></div><p style="margin-top:4px">${esc(r.text)}</p></div><button class="btn btn-ghost btn-sm" data-act="hideRev" data-i="${i}">${h?'Restore':'Hide'}</button></div>`;}).join('')}</div>`;
ACT.hideRev=el=>{const i=+el.dataset.i;S.reviewsHidden.has(i)?S.reviewsHidden.delete(i):S.reviewsHidden.add(i);render();};
DASH.admin.campaigns=()=>dhead('Campaigns','Open campaign briefs from businesses.')+`<div class="card">${table([['Campaign'],['Business'],['Budget','num'],['Applications','num'],['Status']],CAMPAIGNS.map(k=>({go:'campaigns',cells:[`<b>${esc(k.title)}</b>`,esc(B(k.b).name),tk(k.budget),k.apps,'<span class="pill p-good">Live</span>']})))}</div>`;
DASH.admin.reports=()=>dhead('Reports','Marketplace performance, Apr–Sep 2026.')+`<div class="grid g2"><div class="card pad"><h3>GMV (৳ lakh)</h3>${barChart(GMV,{fmt:v=>v+'L',label:'GMV'})}</div><div class="card pad"><h3>BitPromo revenue (৳ lakh)</h3>${barChart(GMV.map(([m,v])=>[m,+(v*.2).toFixed(2)]),{fmt:v=>(+v.toFixed(2))+'L',label:'Revenue'})}</div>
 <div class="card pad"><h3 style="margin-bottom:14px">Orders by category</h3><div class="bars">${[['Food Creators',24],['Influencers',21],['Actors',14],['Comedians',12],['Presenters',10],['Voice Artists',9],['Others',10]].map(([k,v])=>`<div class="bar-row"><span>${k}</span><div class="bar-track"><i style="width:${v*4}%"></i></div><span class="tnum small muted">${v}%</span></div>`).join('')}</div></div>
 <div class="card pad"><h3 style="margin-bottom:14px">Orders by city</h3><div class="bars">${[['Dhaka',58],['Chattogram',16],['Sylhet',9],['Rajshahi',7],['Khulna',6],['Cumilla',4]].map(([k,v])=>`<div class="bar-row"><span>${k}</span><div class="bar-track"><i style="width:${v*1.6}%;background:var(--good)"></i></div><span class="tnum small muted">${v}%</span></div>`).join('')}</div></div></div>`;
DASH.admin.settings=()=>dhead('Platform settings','Marketplace rules applied to every order.')+`<form class="card pad form" data-form="saved"><div><label for="as-1">Commission rate (%)</label><input class="field" id="as-1" value="20" type="number"></div><div><label for="as-2">Auto-approve after buyer silence (days)</label><input class="field" id="as-2" value="3" type="number"></div><div><label for="as-3">Default revisions (Basic)</label><input class="field" id="as-3" value="1" type="number"></div><div><label for="as-4">Creator payout hold after approval (days)</label><input class="field" id="as-4" value="2" type="number"></div><div class="full"><label for="as-5">Community guidelines URL</label><input class="field" id="as-5" value="bitpromo.com.bd/guidelines"></div><div class="full"><button class="btn btn-pri" type="submit">Save settings</button></div></form>`;

/* ===== CAMPAIGNS ===== */
PAGES.campaigns=()=>{const cats=['All',...new Set(CAMPAIGNS.map(k=>k.cat))];const list=CAMPAIGNS.filter(k=>S.campCat==='All'||k.cat===S.campCat);
 return `<div class="phead"><div class="wrap"><div class="crumbs"><button data-go="home">Home</button>${ic('chevr')}<span>Campaigns</span></div><div class="row between"><div><h1 style="font-size:clamp(28px,3.4vw,40px)">Campaign marketplace</h1><p class="muted" style="margin-top:6px;max-width:620px">Businesses post a brief and a budget. Verified creators send proposals. BitPromo protects the payment either way.</p></div><button class="btn btn-pri" data-act="postCamp">${ic('plus')}Post a campaign</button></div></div></div>
 <div class="wrap sec" style="padding-top:28px"><div class="grid g2" style="margin-bottom:32px">${[['Buy Now','Business picks a creator package and orders straight away. Fixed price, fixed delivery.','package','explore','Browse creators'],['Campaign','Business publishes a campaign. Creators apply with a price and an idea. Business hires the best fit.','megaphone',null,'Post a campaign']].map(([h,p,i,g,l])=>`<div class="card pad row" style="flex-wrap:nowrap;align-items:flex-start;gap:16px"><span class="fi" style="width:46px;height:46px;border-radius:12px;display:grid;place-items:center;background:var(--accent-soft);color:var(--accent);flex:none">${ic(i)}</span><div class="stack" style="gap:6px"><span class="eyebrow">Model</span><h3>${h}</h3><p class="muted small">${p}</p><button class="btn-link" ${g?`data-go="${g}"`:'data-act="postCamp"'}>${l} ${ic('arrow')}</button></div></div>`).join('')}</div>
 <div class="chips" style="margin-bottom:22px">${cats.map(c=>`<button class="chipt ${S.campCat===c?'on':''}" data-act="campCat" data-v="${c}">${c}</button>`).join('')}</div>
 <div class="grid g3">${list.map(campCard).join('')}</div></div>`;};
ACT.campCat=el=>{S.campCat=el.dataset.v;render();};
ACT.apply=el=>{const k=CAMPAIGNS.find(x=>x.id===el.dataset.id);modal(`${mhead('Apply for campaign')}<form class="modal-body" data-form="apply" data-id="${k.id}"><div class="row">${bizAv(B(k.b),40)}<div><b>${esc(k.title)}</b><div class="small muted">${esc(B(k.b).name)} · budget ${tk(k.budget)}</div></div></div><div><label class="small" style="font-weight:650" for="ap-p">Your price (৳)</label><input class="field" id="ap-p" type="number" value="${k.budget-1000}"></div><div><label class="small" style="font-weight:650" for="ap-m">Your idea</label><textarea class="field" id="ap-m">I’d film this as a short story with a real reaction moment, delivered in ${k.days-1} days. Script included.</textarea></div><p class="small muted">Applying as Ayesha Rahman (demo creator). You’ll receive 80% of the agreed price.</p><button class="btn btn-pri" type="submit">Send proposal</button></form>`);};
FORM.apply=f=>{S.applied.add(f.dataset.id);closeModal();toast('Proposal sent to the business');render();};
ACT.postCamp=()=>modal(`${mhead('Post a campaign')}<form class="modal-body" data-form="postCamp"><div><label class="small" style="font-weight:650" for="pc-t">Campaign title</label><input class="field" id="pc-t" name="t" value="Weekend brunch launch video" required></div><div class="form"><div><label for="pc-b">Budget (৳)</label><input class="field" id="pc-b" name="b" type="number" value="20000"></div><div><label for="pc-d">Deadline (days)</label><input class="field" id="pc-d" name="d" type="number" value="10"></div><div><label for="pc-c">Creator type</label><select class="field" id="pc-c" name="c">${CATS.map(c=>`<option>${c.n}</option>`).join('')}</select></div><div><label for="pc-p">Platform</label><select class="field" id="pc-p" name="p"><option>Facebook</option><option>Instagram</option><option>TikTok</option><option>YouTube</option></select></div></div><div><label class="small" style="font-weight:650" for="pc-x">What do you need?</label><input class="field" id="pc-x" name="x" value="30-second video featuring our new brunch menu"></div><button class="btn btn-pri" type="submit">Publish campaign</button></form>`);
FORM.postCamp=f=>{const id='k'+(CAMPAIGNS.length+1);CAMPAIGNS.unshift({id,b:ME_BIZ,title:f.t.value,budget:+f.b.value||10000,city:'Dhaka',content:f.x.value,days:+f.d.value||7,apps:0,cat:f.c.value,plat:f.p.value});S.myCamps.unshift(id);if(!S.role)S.role='biz';closeModal();toast('Campaign published. Creators can apply now.');render();};

/* ===== LANDINGS ===== */
PAGES.business=()=>`<section class="hero"><div class="wrap hero-in"><div><span class="eyebrow" style="color:var(--accent)">For businesses</span><h1 style="margin-top:14px">Your brand deserves a face <span>people trust.</span></h1><p class="hero-sub">Work with verified Bangladeshi creators, actors and influencers. Brief them clearly, pay safely, and approve every video before it goes live.</p><div class="hero-ctas"><button class="btn btn-light btn-lg" data-go="explore">Find a Creator</button><button class="btn btn-outline-light btn-lg" data-act="postCamp">Launch a campaign</button></div></div>
 <div class="grid g2" style="gap:14px">${['c7','c4','c13','c2'].map((id,i)=>vt(C(id),{r:'v',i,title:['Food','Brand film','Beauty','Tech'][i]})).join('')}</div></div></section>
 <section class="sec"><div class="wrap"><div class="sec-head"><h2>Everything a business needs to get a promo video made</h2></div><div class="grid g3">${[['compass','Find creators','Search 20+ categories by city, language, audience and budget.'],['megaphone','Launch campaigns','Post a brief and budget, and let creators pitch you.'],['video','Create promotional videos','Fixed packages from 15-second reels to 60-second brand films.'],['users','Reach new audiences','Tap into creators’ followers on Facebook, Instagram, TikTok and YouTube.'],['badge','Work with verified creators','Identity, social profile and portfolio checked before they can sell.'],['lock','Protected payment','Your money stays with BitPromo until you approve the video.']].map(([i,h,p])=>`<div class="card pad feat"><span class="fi">${ic(i)}</span><div><h4>${h}</h4><p class="muted small">${p}</p></div></div>`).join('')}</div></div></section>
 <section class="sec sec-alt"><div class="wrap"><div class="sec-head"><h2>How your money is protected</h2></div>${escrowFlow()}</div></section>
 <section class="sec"><div class="wrap"><div class="sec-head"><h2>Creators businesses book most</h2><button class="btn btn-ghost btn-sm" data-go="explore">See all</button></div><div class="grid g4">${['c1','c7','c5','c12'].map((id,i)=>creatorCard(C(id),i)).join('')}</div></div></section>
 <section class="sec" style="padding-top:0"><div class="wrap"><div class="final"><h2>Find the creator. Create the content. Grow your brand.</h2><div class="row" style="justify-content:center;margin-top:24px"><button class="btn btn-light btn-lg" data-go="explore">Find a Creator</button><button class="btn btn-outline-light btn-lg" data-go="join">Create business account</button></div></div></div></section>`;
PAGES.creators=()=>`<section class="hero"><div class="wrap hero-in"><div><span class="eyebrow" style="color:var(--accent)">For creators</span><h1 style="margin-top:14px">Turn your influence <span>into income.</span></h1><p class="hero-sub">Create promotional content for brands, get paid for your work, and grow your professional opportunities through BitPromo.</p><div class="hero-ctas"><button class="btn btn-light btn-lg" data-go="join~creator">Become a Creator</button><button class="btn btn-outline-light btn-lg" data-go="dash~creator~home">Preview the creator dashboard</button></div></div>
 <div class="card pad stack" style="background:var(--night-2);border-color:var(--night-line);color:var(--on-night);gap:16px"><h3>Earnings calculator</h3><div><div class="row between small"><label for="calc-p">Your package price</label><b class="tnum" id="calc-pv">৳10,000</b></div><input type="range" id="calc-p" min="2000" max="50000" step="1000" value="10000" data-calc></div><div><div class="row between small"><label for="calc-n">Orders per month</label><b class="tnum" id="calc-nv">8</b></div><input type="range" id="calc-n" min="1" max="30" value="8" data-calc></div>
 <div style="border-top:1px solid var(--night-line);padding-top:14px"><div class="small" style="color:var(--on-night-2)">You could earn per month</div><div class="pkg-price" style="color:var(--ink);font-size:40px" id="calc-out">৳64,000</div><div class="small" style="color:var(--on-night-2)" id="calc-sub">After BitPromo’s 20% commission (৳16,000)</div></div></div></div></section>
 <section class="sec"><div class="wrap"><div class="sec-head"><h2>Why creators join BitPromo</h2></div><div class="grid g4">${[['wallet','Earn from your audience','Turn followers into paid brand work.'],['briefcase','Work with brands','Restaurants, fashion labels, startups and more.'],['sliders','Set your own prices','Three packages, your rates, your delivery times.'],['package','Manage orders','Briefs, files, chat and deadlines in one place.'],['film','Build your portfolio','Every approved video can go on your profile.'],['lock','Secure transactions','Payment is secured before you start filming.'],['shield','Scope protection','Revision limits stop endless change requests.'],['trend','Grow your profile','Ratings and verified status bring repeat buyers.']].map(([i,h,p])=>`<div class="feat"><span class="fi">${ic(i)}</span><div><h4>${h}</h4><p class="muted small">${p}</p></div></div>`).join('')}</div></div></section>
 <section class="sec sec-alt"><div class="wrap"><div class="sec-head"><div><h2>Become a verified BitPromo creator</h2><p class="muted">Seven steps from sign-up to your verified badge.</p></div><button class="btn btn-pri" data-go="verify">Start verification</button></div>${vsteps(0)}</div></section>`;
POST.creators=()=>calc();
function calc(){const p=+($('#calc-p')||{}).value||10000,n=+($('#calc-n')||{}).value||8;if(!$('#calc-out'))return;$('#calc-pv').textContent=tk(p);$('#calc-nv').textContent=n;$('#calc-out').textContent=tk(p*n*.8);$('#calc-sub').textContent=`After BitPromo’s 20% commission (${tk(p*n*.2)})`;}
document.addEventListener('input',e=>{if(e.target.dataset&&'calc' in e.target.dataset)calc();});
PAGES.how=()=>`<div class="phead"><div class="wrap"><div class="crumbs"><button data-go="home">Home</button>${ic('chevr')}<span>How it works</span></div><h1 style="font-size:clamp(28px,3.4vw,40px)">From idea to promotional video. One platform.</h1><p class="muted" style="margin-top:8px;max-width:640px">BitPromo is a trusted promotional-content marketplace: discovery, content creation, secure payment and quality control in one flow.</p></div></div>
 <section class="sec"><div class="wrap">${steps4()}</div></section>
 <section class="sec sec-alt"><div class="wrap"><div class="sec-head"><div><h2>Two ways to buy</h2></div></div><div class="grid g2">${[['Buy Now','Pick a creator’s Basic, Standard or Premium package and order immediately.','explore','Browse creators'],['Campaign','Post your brief and budget. Creators apply and you choose the best proposal.','campaigns','See campaigns']].map(([h,p,g,l])=>`<div class="card pad stack"><h3>${h}</h3><p class="muted">${p}</p><button class="btn btn-ghost btn-sm" style="align-self:flex-start" data-go="${g}">${l}</button></div>`).join('')}</div></div></section>
 <section class="sec"><div class="wrap"><div class="sec-head"><div><h2>Every order follows the same eight stages</h2><p class="muted">Both sides see exactly where the order is, and BitPromo steps in at quality check.</p></div><button class="btn btn-ghost btn-sm" data-go="track~BP-24117">See a live order</button></div><div class="card pad"><div class="hstl">${STAGES.map((s,i)=>`<div class="${i<6?'done':''} ${i===6?'cur':''}">${s}</div>`).join('')}</div></div></div></section>
 <section class="sec sec-alt"><div class="wrap"><div class="sec-head"><h2>Your money is protected</h2></div>${escrowFlow()}<div class="card pad" style="margin-top:22px;max-width:560px"><h3 style="margin-bottom:12px">Revenue model: 20% marketplace commission</h3><div class="sumrow"><span>Creator service price</span><b>৳20,000</b></div><div class="sumrow" style="margin-top:6px"><span>BitPromo</span><b style="color:var(--accent)">৳4,000</b></div><div class="sumrow" style="margin:6px 0 14px"><span>Creator</span><b style="color:var(--good)">৳16,000</b></div>${splitBar(20000)}</div></div></section>`;
PAGES.trust=()=>`<div class="phead"><div class="wrap"><div class="crumbs"><button data-go="home">Home</button>${ic('chevr')}<span>Trust &amp; Safety</span></div><h1 style="font-size:clamp(28px,3.4vw,40px)">Trust &amp; Safety</h1><p class="muted" style="margin-top:8px;max-width:640px">How BitPromo keeps both sides safe, from the first message to the final payout.</p></div></div>
 <section class="sec"><div class="wrap"><div class="grid g2" style="gap:18px">${[['badge','Creator verification','Identity documents, social profile ownership and a portfolio review before a creator can sell.'],['building','Business verification','Trade licence or business page checks for buyers placing large orders.'],['lock','Secure marketplace transactions','Payments are held through BitPromo’s marketplace process and released after approval.'],['doc','Order documentation','Brief, files, messages and every status change are saved on the order.'],['eye','Content requirements','Videos are checked against the agreed brief: length, branding, offer text and format.'],['refresh','Revision rules','Each package states its revisions. Changes outside the brief need a new order.'],['scale','Dispute resolution','A structured review of the order record, with refund, release or split outcomes.'],['flag','Report system','Report a profile, message or video in two taps. Our team reviews every report.'],['alert','Fraud prevention','Off-platform payment requests are flagged, and suspicious accounts are paused.'],['users','Community guidelines','Respectful communication, honest reviews and lawful content for both sides.']].map(([i,h,p])=>`<div class="card pad feat"><span class="fi">${ic(i)}</span><div><h4>${h}</h4><p class="muted small">${p}</p></div></div>`).join('')}</div>
 <div class="demo-note" style="margin-top:24px">${ic('alert')}BitPromo is a marketplace, not a bank. Live payments would run through a licensed payment provider.</div></div></section>`;

/* ===== VERIFY ===== */
const VSTEPS=['Create profile','Identity','Social profiles','Portfolio','Submit','BitPromo review','Verified badge'];
function vsteps(cur){return `<div class="vsteps">${VSTEPS.map((s,i)=>`<div class="vstep ${i<cur?'done':''} ${i===cur?'cur':''}"><i>${i<cur?'✓':i+1}</i>${s}</div>`).join('')}</div>`;}
PAGES.verify=()=>{const v=S.ver,st=v.step;let body='';
 if(st===1)body=`<h2 style="font-size:22px">Create your creator profile</h2><div class="form" style="margin-top:16px"><div><label for="vf-1">Full name</label><input class="field" id="vf-1" value="Rumana Akhter"></div><div><label for="vf-2">City</label><select class="field" id="vf-2"><option>Dhaka</option><option>Chattogram</option><option>Sylhet</option></select></div><div><label for="vf-3">Main category</label><select class="field" id="vf-3">${CATS.map(c=>`<option>${c.n}</option>`).join('')}</select></div><div><label for="vf-4">Languages</label><input class="field" id="vf-4" value="Bangla, English"></div><div class="full"><label for="vf-5">Short bio</label><textarea class="field" id="vf-5">Home cook and food reviewer sharing Dhaka’s best street food and family recipes.</textarea></div></div>`;
 if(st===2)body=`<h2 style="font-size:22px">Upload identity information</h2><p class="muted" style="margin:6px 0 16px">Used only to confirm you are who you say you are. Not shown to buyers.</p><div class="grid g3" style="gap:12px">${[['nidf','NID front'],['nidb','NID back'],['selfie','Selfie holding NID']].map(([k,l])=>`<div class="drop" style="align-items:center;text-align:center"><span class="fi" style="width:44px;height:44px;border-radius:12px;background:var(--bg-2);display:grid;place-items:center;color:var(--muted)">${ic('id')}</span><b class="small">${l}</b>${v.files[k]?`<span class="filechip">${ic('check')}${esc(v.files[k])}</span>`:`<label class="btn btn-ghost btn-sm" for="vu-${k}" style="cursor:pointer">Upload</label><input type="file" id="vu-${k}" data-vup="${k}" accept="image/*" hidden>`}</div>`).join('')}</div><button class="btn-link" style="margin-top:12px" data-act="vSample">Use sample documents</button>`;
 if(st===3)body=`<h2 style="font-size:22px">Add your social profiles</h2><p class="muted" style="margin:6px 0 16px">We confirm you own these accounts and check follower numbers.</p><div class="form">${['Facebook','Instagram','YouTube','TikTok'].map(p=>`<div><label for="vs-${p}">${p}</label><input class="field" id="vs-${p}" value="${p.toLowerCase()}.com/rumana.eats"></div>`).join('')}</div>`;
 if(st===4)body=`<h2 style="font-size:22px">Add your portfolio</h2><p class="muted" style="margin:6px 0 16px">Upload 3–6 videos that show your on-camera style.</p><div class="grid g4 keep2">${Array.from({length:4},(_,i)=>vt({id:'c7',look:VERIFY_QUEUE[0].look},{r:'v',title:['Street food tour','Recipe reel','Café review','Brand shoutout'][i],i})).join('')}</div>`;
 if(st===5)body=`<h2 style="font-size:22px">Review and submit</h2><ul class="checks" style="margin:16px 0">${['Profile details complete','3 identity documents uploaded','4 social profiles linked','4 portfolio videos added'].map(x=>`<li>${ic('check')}${x}</li>`).join('')}</ul><label class="row" style="gap:10px;font-weight:500"><input type="checkbox" id="v-agree" checked> I agree to BitPromo’s creator terms and community guidelines.</label>`;
 if(st===6)body=`<div style="text-align:center;padding:20px 0" class="stack"><div class="spinner"></div><h2 style="font-size:22px">BitPromo is reviewing your application</h2><p class="muted">Reviews usually take 1–2 working days. We’ll message you when it’s done.</p><button class="btn btn-ghost btn-sm" style="align-self:center" data-act="vNext">Prototype: simulate approval</button></div>`;
 if(st===7)body=`<div style="text-align:center;padding:20px 0" class="stack"><div class="success-ic">${ic('badge')}</div><h2>You’re a Verified Creator ✓</h2><p class="muted">Your badge now shows on your profile and every listing.</p><div class="row" style="justify-content:center"><span class="verified-chip" style="font-size:15px;padding:6px 14px 6px 8px">${vb()}Verified Creator</span></div><button class="btn btn-pri" style="align-self:center" data-go="dash~creator~home">Go to creator dashboard</button></div>`;
 return `<div class="phead"><div class="wrap"><div class="crumbs"><button data-go="creators">For creators</button>${ic('chevr')}<span>Verification</span></div><h1 style="font-size:clamp(26px,3vw,36px)">Become a verified BitPromo creator</h1></div></div>
 <div class="wrap" style="padding-block:28px 64px;max-width:900px"><div class="card pad" style="margin-bottom:20px">${vsteps(st-1)}</div><div class="card pad" style="padding:clamp(18px,3vw,28px)">${body}</div>
 ${st<6?`<div class="row between" style="margin-top:18px">${st>1?`<button class="btn btn-ghost" data-act="vBack">${ic('chevl')}Back</button>`:'<span></span>'}<button class="btn btn-pri" data-act="vNext">${st===5?'Submit application':'Continue'}${ic('chevr')}</button></div>`:''}
 <p class="small muted" style="margin-top:18px">Verification is a platform status. It confirms these steps were completed. It does not guarantee a person’s identity or reputation beyond this process.</p></div>`;};
ACT.vNext=()=>{if(S.ver.step===5&&!$('#v-agree').checked){toast('Please accept the creator terms');return;}S.ver.step=Math.min(7,S.ver.step+1);if(S.ver.step===7)S.role='creator';render();window.scrollTo(0,0);};
ACT.vBack=()=>{S.ver.step=Math.max(1,S.ver.step-1);render();};
ACT.vSample=()=>{S.ver.files={nidf:'NID_front.jpg',nidb:'NID_back.jpg',selfie:'Selfie_with_NID.jpg'};render();};

/* ===== AUTH ===== */
PAGES.signin=()=>`<div class="auth"><div class="auth-art"><span class="eyebrow" style="color:var(--accent)">Welcome back</span><h2 style="font-size:40px">Your brand. Their influence. One powerful video.</h2><div class="grid g3" style="gap:10px;max-width:440px">${['c1','c5','c9'].map((id,i)=>vt(C(id),{r:'v',i})).join('')}</div></div>
 <div class="auth-form"><h1 style="font-size:32px">Sign in to BitPromo</h1><p class="muted">Pick a demo account to explore each side of the marketplace.</p>
 <div class="stack" style="gap:10px">${[['biz','Business demo','business@bitpromo.demo · Bhoj Kitchen','#FF7A59','building'],['creator','Creator demo','creator@bitpromo.demo · Ayesha Rahman','#2453FF','film'],['admin','Admin demo','admin@bitpromo.demo · BitPromo team','#0A1020','shield']].map(([r,t,s,c,i])=>`<button class="demo-acc" data-act="signinAs" data-r="${r}"><span class="fi" style="background:${c}">${ic(i)}</span><div class="grow"><b>${t}</b><div class="small muted">${s}</div></div>${ic('chevr')}</button>`).join('')}</div>
 <div class="row" style="gap:12px;color:var(--muted)"><span style="flex:1;height:1px;background:var(--line)"></span><span class="small">or sign in with email</span><span style="flex:1;height:1px;background:var(--line)"></span></div>
 <form class="stack" data-form="signin"><div><label class="small" style="font-weight:650" for="si-e">Email</label><input class="field" id="si-e" name="e" type="email" value="business@bitpromo.demo"></div><div><label class="small" style="font-weight:650" for="si-p">Password</label><input class="field" id="si-p" name="p" type="password" value="demo1234"></div><button class="btn btn-pri btn-block" type="submit">Sign in</button></form>
 <p class="small muted">New to BitPromo? <button class="btn-link" data-go="join">Create an account</button></p></div></div>`;
FORM.signin=f=>{const e=f.e.value.trim().toLowerCase();const r=Object.keys(USERS).find(k=>USERS[k].email===e);if(!r){toast('Use one of the three demo emails above');return;}ACT.signinAs({dataset:{r}});};
ACT.signinAs=el=>{const r=el.dataset.r;S.role=r;S.thread=null;go(`dash~${r}~${r==='admin'?'overview':'home'}`);};
ACT.signout=()=>{S.role=null;toast('Signed out');go('home');};
PAGES.join=(role)=>{S.joinRole=role==='creator'?'creator':S.joinRole||'biz';const r=S.joinRole;return `<div class="auth"><div class="auth-art"><span class="eyebrow" style="color:var(--accent)">Get started</span><h2 style="font-size:40px">${r==='creator'?'Turn your influence into income.':'Find the right face for your brand.'}</h2><ul class="checks" style="color:var(--on-night)">${(r==='creator'?['Set your own prices','Get paid after approval','Verified badge on your profile']:['Verified creators across Bangladesh','Payment held until you approve','Quality check on every video']).map(x=>`<li>${ic('check')}${x}</li>`).join('')}</ul></div>
 <div class="auth-form"><h1 style="font-size:32px">Create your account</h1><div class="role-pick">${[['biz','I’m a business','Hire creators for promotional videos','building'],['creator','I’m a creator','Sell promotional video content','film']].map(([k,t,s,i])=>`<button class="${r===k?'on':''}" data-act="joinRole" data-r="${k}"><span style="color:var(--accent)">${ic(i)}</span><b>${t}</b><span class="small muted">${s}</span></button>`).join('')}</div>
 <form class="stack" data-form="join">${r==='biz'?`<div><label class="small" style="font-weight:650" for="j-b">Business name</label><input class="field" id="j-b" value="Bhoj Kitchen"></div><div><label class="small" style="font-weight:650" for="j-t">Business type</label><select class="field" id="j-t"><option>Restaurant</option><option>Fashion brand</option><option>E-commerce</option><option>Startup</option><option>Real estate</option><option>Education</option><option>Other</option></select></div>`:`<div><label class="small" style="font-weight:650" for="j-n">Full name</label><input class="field" id="j-n" value="Rumana Akhter"></div>`}
 <div><label class="small" style="font-weight:650" for="j-e">Email</label><input class="field" id="j-e" type="email" value="${r==='biz'?'business':'creator'}@bitpromo.demo"></div><div><label class="small" style="font-weight:650" for="j-p">Password</label><input class="field" id="j-p" type="password" value="demo1234"></div>
 <button class="btn btn-pri btn-block" type="submit">${r==='biz'?'Create business account':'Continue to verification'}</button></form><p class="small muted">Already have an account? <button class="btn-link" data-go="signin">Sign in</button></p></div></div>`;};
ACT.joinRole=el=>{S.joinRole=el.dataset.r;render();};
FORM.join=()=>{if(S.joinRole==='creator'){S.ver.step=1;go('verify');toast('Account created. Let’s get you verified.');}else{S.role='biz';go('dash~biz~home');toast('Business account created');}};
PAGES.messages=()=>{const r=S.role||'biz';ROUTE=`dash~${r}~messages`;return PAGES.dash(r,'messages');};

/* ===== menu / drawer ===== */
ACT.menu=()=>{const u=S.role;const L=(g,l,i)=>`<button class="dl" data-go="${g}">${ic(i)}${l}</button>`;
 $('#modal-root').innerHTML=`<div class="drawer" data-act="bg"><div class="drawer-in"><div class="row between" style="margin-bottom:10px"><button class="logo" data-go="home"><span class="logo-mark">${ic('play','i-fill')}</span><span>Bit<b>Promo</b></span></button><button class="iconbtn" data-act="close" aria-label="Close menu">${ic('x')}</button></div>
 ${u?`<div class="row" style="padding:10px;border:1px solid var(--line);border-radius:12px;margin-bottom:8px">${userAv(40)}<div><b>${USERS[u].name}</b><div class="small muted">${USERS[u].email}</div></div></div>${L(`dash~${u}~${u==='admin'?'overview':'home'}`,'Dashboard','grid')}`:''}
 ${L('home','Home','home')}${L('explore','Explore Creators','compass')}${L('categories','Categories','grid')}${L('how','How It Works','refresh')}${L('business','For Businesses','building')}${L('creators','For Creators','film')}${L('campaigns','Campaigns','megaphone')}${L('trust','Trust & Safety','shield')}
 <div style="margin-top:auto;display:flex;flex-direction:column;gap:8px;padding-top:16px">${u?`<button class="btn btn-ghost btn-block" data-act="signout">${ic('logout')}Sign out</button>`:`<button class="btn btn-ghost btn-block" data-go="signin">Sign In</button><button class="btn btn-pri btn-block" data-go="join">Get Started</button><button class="btn btn-ghost btn-block" data-go="creators">Become a Creator</button>`}</div></div></div>`;};
